<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title><?= $v_title_page;?></title>

  <?php
    include_once 'app/views/public/adm/head.phtml';
  ?>
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
  <div class="wrapper">
    <!-- Navbar -->
    <?php
      include_once 'app/views/public/adm/topNavigation.phtml';
    ?>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar elevation-4 sidebar-light-warning">
      <!-- Brand Logo -->
      <?php
        include_once 'app/views/public/adm/logo.phtml';
      ?>
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <?php
        include_once 'app/views/public/adm/userInfo.phtml';
        ?>
        <!-- Sidebar Menu -->
        <?php
        include_once 'app/views/public/menuLateral.phtml';
        ?>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark"><?= $v_page_context;?></h1>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- Main row -->
          <form role="form" id="formPerfil" method="POST" action="<?= $v_page_url;?>actualizar">
          <div class="row">
            <!-- / Corpo da página INÍCIO -->

            <div class="col-6">
            
              <div class="card">

                <div class="card-body">
                  <div class="form-group">
                    <label for="nome-perfil">Nome</label>
                    <input type="text" name="nome" class="form-control" id="nome-perfil" placeholder="Nome do <?= $v_page_context;?>" value="<?= ucfirst(Method::lowerGeneral($v_entity->getNome())); ?>">
                    <input type="hidden" value="<?= $v_entity->getID();?>" name="id_perfil">
                  </div>
                  <div class="form-group">
                    <label for="descricao-perfil">Descrição</label>
                    <textarea name="descricao" rows="4" class="form-control" id="descricao-perfil" placeholder="Descrição do <?= $v_page_context;?>" ><?= rtrim(ltrim($v_entity->getDescricao())); ?></textarea>
                  </div>
                </div>
                <!-- /.card-body -->
                <!--<div class="card-footer">
                  <button type="submit" class="btn btn-primary">Gravar <?= $v_page_context;?></button>
                </div>-->
                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                    <a style="cursor:pointer" onclick="voltar();" class="btn btn-default btn-circle" title="Voltar"><i
                        class="fa fa-chevron-left"></i><strong> Voltar</strong></a>
                    <button type="submit" class="btn btn-primary">Actualizar <?= $v_page_context;?></button>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-6">
              <div class="card">
              <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Permissão</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (isset($v_permissoes)) {
                                    if (empty($v_permissoes)) {
                                        ?>
                                    <div class="alert alert-danger">
                                        <strong><span class="fa fa-info"></span></strong> Até o momento não temos escola adicionada.
                                    </div>
                                    <?php
                                }
                                $cont = 0;
                                foreach ($v_permissoes as $v_permissao) {
                                    ?>
                                <tr>
                                    <td>
                                      <input type="checkbox" name="permissoes[]" id="checkbox" value="<?= $v_permissao->getId() ?>" class="custom-check"
                                        <?php
                                            foreach ($v_entity->getPermissoes() as $v_permissaoAtribuida) {
                                              if($v_permissao->getId() === $v_permissaoAtribuida->getId())
                                              {
                                                echo 'checked';
                                              }
                                            } ?> />
                                    </td>
                                    <td><?= $v_permissao->getDescricao() ?></td>
                                </tr>
                                <?php }
                                } ?>
                            </tbody>
                        </table>
                    </div>
              

                                
                            
              </div>
            </div>
            <!-- / Corpo da página FIM -->
          </div>
          </form>
          <!-- /.row -->
        </div>
        <!--/. container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <?php
    include_once 'app/views/public/adm/foot.phtml';
    ?>

  </div>
  <!-- ./wrapper -->

  <?php
    include_once 'app/views/public/adm/javascript.phtml';
    include_once 'app/views/public/adm/datatables.phtml';
  ?>
  <script type="text/javascript">
$(document).ready(function () {
  $.validator.setDefaults({
  });
  $('#formPerfil').validate({
    rules: {
      nome: {
        required: true
      },
      descricao: {
        required: true,
        minlength: 10
      },
      terms: {
        required: true
      },
    },
    messages: {
      nome: {
        required: "Por favor, insira o nome do perfil"
      },
      descricao: {
        required: "É necessário que descreva o Perfil para melhor detalhes",
        minlength: "Descrição é muito curta. Deve ter mais de 10 caracteres."
      }
      /*,
      terms: "Please accept our terms"*/
    },
    errorElement: 'span',
    errorPlacement: function (error, element) {
      error.addClass('invalid-feedback');
      element.closest('.form-group').append(error);
    },
    highlight: function (element, errorClass, validClass) {
      $(element).addClass('is-invalid');
    },
    unhighlight: function (element, errorClass, validClass) {
      $(element).removeClass('is-invalid');
    }
  });
});
</script>
</body>

</html>