<div class="modal fade" id="fotorosto" tabindex="-1" role="dialog" aria-labelledby="fotorostoTitulo" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog-centered" role="document">

        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle"><i class="fa fa-file-o fa-1x"></i> Carregar foto de rosto para o Produto</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger" id="label-erros" style="display:none;">
                    <strong></strong> <span id="info-erros"></span> <a href="#" class="alert-link"></a>
                </div>
                <form id="upload-foto" class="form-horizontal form-label-left" data-parsley-validate="" novalidate="" method="POST" action="<?= $v_page_url ?>novafoto" enctype="multipart/form-data">
                    <input type="file" id="foto_produto" name="foto_produto" class="form-control col-md-7 col-xs-12" required>
                    <input type="hidden" value="<?= $v_entity->getId(); ?>" name="id_produto">
                </form>
            </div>
            <div class="modal-footer">
                <button id = "enviar-foto" type="button" class="btn btn-success" onclick="return verificacao();">Gravar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>

    </div>
</div>
<script>
    function verificacao()
    {
        if($("#foto_produto").val()=="")
        {
            $("#label-erros").show();
            $("#info-erros").text("Escolha um ficheiro de imagem para continuar...");
            return false;
        }
        else
        {
            var form = document.getElementById("upload-foto");
            document.getElementById("enviar-foto").addEventListener("click", function () {
                form.submit();
            });return true;
        }
    }
</script>