<!-- Modal -->
<div class="modal fade" id="inscricaoModal" tabindex="-1" aria-labelledby="inscricaoModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="inscricaoModalLabel">Ficha de Inscrição</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <!--<form role="form" id="formProduto" method="POST" action="<?= $v_page_url; ?>registar">-->
            <form class="form-horizontal" id="mail-express" autocomplete="off">
                <div class="modal-body">
                    <div id="processando" style="text-align:center; display:none;">
                        <img src="/intercolegial/web-files/images/loader.gif" alt="">
                    </div><br>
                    <div class="alert alert-success alert-dismissable" role="alert" id="divSucesso" style="display: none;">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        A inscrição foi feita com sucesso. Verifique a sua caixa de email para activação da conta.
                    </div>
                    <div class="alert alert-warning alert-dismissable" role="alert" id="divEmailExistente" style="display: none;">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        O email já existe.
                    </div>

                    <div class="alert alert-warning alert-dismissable" role="alert" id="divError" style="display: none;">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        A sua inscrição foi com sucesso, mas não foi possível enviar o link para activação da conta.<br>
                        <b>Por favor contacte-nos.</b>
                    </div>

                    <div class="alert alert-warning alert-dismissable" role="alert" id="divVazio" style="display: none;">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        Por favor, preencha o formulário
                    </div>

                    <div class="alert alert-danger" id="label-erro" style="display:none;">
                        <strong></strong> <span id="info-erro"></span> <a href="#" class="alert-link"></a>
                    </div>

                    <div class="card-body">
                        <div class="form-group">
                            <label for="nome-estudante">Nome</label>
                            <input type="text" name="nome" class="form-control" id="nome-estudante" placeholder="Seu nome" required>
                        </div>
                        <div class="form-group">
                            <label for="email-estudante">Email</label>
                            <input type="email" name="email" class="form-control" id="email-estudante" placeholder="Seu email" required>
                        </div>
                        <div class="form-group">
                            <label for="telefone-estudante">Telefone</label>
                            <input type="number" name="telefone" class="form-control" id="telefone-estudante" placeholder="Seu telefone" required>
                        </div>
                        <div class="form-group">
                            <label for="escola">Escola</label>
                            <select class="form-control select2" style="width: 100%;" name="escola" id="escola" required>
                                <option value="">-- Escolha a sua escola --</option>
                                <?php
                                if (isset($v_escolas)) {
                                    if (empty($v_escolas)) {
                                        echo "Sem escola";
                                    }
                                    foreach ($v_escolas as $escola) {
                                ?>
                                        <option value="<?= $escola->getId(); ?>"><?= $escola->getNome(); ?></option>
                                <?php
                                    }
                                }
                                ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="passe-estudante">Palavra-passe</label>
                            <input type="password" name="passe" class="form-control" id="passe-estudante" placeholder="Crie a Palavra-passe" required>
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <!---
                    <div class="card-footer">
                        <a style="cursor:pointer" onclick="voltar();" class="btn btn-default btn-circle" title="Voltar"><i class="fa fa-chevron-left"></i><strong> Voltar</strong></a>
                        <button type="submit" class="btn btn-primary">Gravar <?= $v_page_context; ?></button>
                    </div>
                    -->

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button id="submit-email" type="button" class="btn btn-primary">Inscrever-se</button>
                </div>
            </form>
        </div>
    </div>
</div>