<footer>
    <div class="container">
        <div class="row justify-content-center">

            <div class="col-md-4 col-12">
                <div class="footer_box">
                    <div class="footer_header">
                        <div class="footer_logo">
                            <img src="/jam/web-files/assets/img/logo.png" alt="JAM">
                        </div>
                    </div>
                    <div class="footer_box_body">
                        <p class="justificado-foot">
                        É uma empresa ligada ao ramo de realizações de Eventos e Agenciamento artístico, sediada em Luanda, Estrada do Patriota, Edifício Kissange, 1º Andar A.
                        </p>
                        <ul class="footer_social">
                            <!--
                            <li>
                                <a href="#"><i class="ion-social-pinterest"></i></a>
                            </li>
                            -->
                            <li>
                                <a href="#"><i class="ion-social-facebook"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="ion-social-twitter"></i></a>
                            </li>
                            <!--
                            <li>
                                <a href="#"><i class="ion-social-dribbble"></i></a>
                            </li>
                            -->
                            <li>
                                <a href="#"><i class="ion-social-instagram"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-4">
                <div class="footer_box">
                    <div class="footer_header">
                        <h4 class="footer_title">
                            instagram
                        </h4>
                    </div>
                    <div class="footer_box_body">
                        <ul class="instagram_list">
                            <li>
                                <a href="#">
                                    <img src="/jam/web-files/assets/img/cleander/c1.png" alt="instagram">
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="/jam/web-files/assets/img/cleander/c2.png" alt="instagram">
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="/jam/web-files/assets/img/cleander/c3.png" alt="instagram">
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="/jam/web-files/assets/img/cleander/c3.png" alt="instagram">
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="/jam/web-files/assets/img/cleander/c2.png" alt="instagram">
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="/jam/web-files/assets/img/cleander/c1.png" alt="instagram">
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-4">
                <div class="footer_box">
                    <div class="footer_header">
                        <h4 class="footer_title">
                            Subscrever a nossa newsletter
                        </h4>
                    </div>
                    <div class="footer_box_body">
                        <div class="newsletter_form">
                            <form action="#" method="POST">
                                <input type="email" class="form-control" required placeholder="Seu email">
                                <button type="submit" class="btn btn-rounded btn-block btn-primary">SUBSCREVER</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<div class="copyright_footer">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-12">
                <p>
                    <?php echo date('Y');?> &copy; JAM ENT &bull; TODOS OS DIREITOS RESERVADOS 
                </p>
            </div>
            <div class="col-12 col-md-6 ">
                <ul class="footer_menu">
                    <li>
                        <a href="<?= $v_page_url;?>">Início</a>
                    </li>
                    <li>
                        <a href="<?= $v_page_url;?>intercolegial">Intercolegial</a>
                    </li>
                    <li>
                        <a href="<?= $v_page_url;?>am">AM</a>
                    </li>
                    <li>
                        <a href="<?= $v_page_url;?>contactos">Contactos</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>