<title><?= $v_title_page;?></title>
    <!-- SEO -->
    <!-- This site is optimized with the Yoast SEO plugin v6.3.1 - https://yoast.com/wordpress/plugins/seo/ -->
    <meta name="description" content="" />
    <meta property="og:locale" content="pt_PT" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="JAM &#8482; Entertainment - Official Website" />
    <meta property="og:description" content="JAM" />
    <meta property="og:url" content="http://jam.co.ao/web-files/assets/img/logo.png" />
    <meta property="og:site_name" content="JAM &#8482; Entertainment - Official Website" />
    <meta property="og:image" content="http://jam.co.ao/web-files/assets/img/logo.png" />
    <meta property="og:image:secure_url" content="http://jam.co.ao/web-files/assets/img/logo.png" />
    <meta name="google:card" content="summary_large_image" />
    <meta name="google:description"	content="JAM" />
    <meta name="google:title" content="JAM &#8482; Entertainment - Official Website" />
    <meta name="google:image" content="http://jam.co.ao/web-files/assets/img/logo.png" />
    <!-- // SEO-->
<!--===============================================================================================-->
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/intercolegial/web-files/adm/plugins/fontawesome-free/css/all.min.css">
  <link rel="stylesheet" href="/intercolegial/web-files/adm/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="/intercolegial/web-files/adm/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/intercolegial/web-files/adm/dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <!-- ========== Favicon Ico ========== -->
  <link rel="icon" href="/intercolegial/web-files/images/icon.png" type="image/ico" />