<title><?= $v_title_page; ?></title>
<!-- SEO -->
<!-- This site is optimized with the Yoast SEO plugin v6.3.1 - https://yoast.com/wordpress/plugins/seo/ -->
<meta name="description" content="O Torneio Intercolegial Tina Tune é um conjunto de festivais de carácter social com a finalidade de colaborar com a formação pedagógica, filosófica e artística dos estudantes, por meio das várias formas de manifestação da arte." />
<meta property="og:locale" content="pt_PT" />
<meta property="og:type" content="website" />
<meta property="og:title" content="Oficial | Torneio Intercolegial Tina Tune" />
<meta property="og:description" content="O Torneio Intercolegial Tina Tune é um conjunto de festivais de carácter social com a finalidade de colaborar com a formação pedagógica, filosófica e artística dos estudantes, por meio das várias formas de manifestação da arte." />
<meta property="og:url" content="https://www.intercolegialtinatune.co.ao/web-files/images/logo_front.png" />
<meta property="og:site_name" content="Oficial | Torneio Intercolegial Tina Tune" />
<meta property="og:image" content="https://www.intercolegialtinatune.co.ao/web-files/images/logo_front.png" />
<meta property="og:image:secure_url" content="https://www.intercolegialtinatune.co.ao/web-files/images/logo_front.png" />
<meta name="google:card" content="summary_large_image" />
<meta name="google:description" content="O Torneio Intercolegial Tina Tune é um conjunto de festivais de carácter social com a finalidade de colaborar com a formação pedagógica, filosófica e artística dos estudantes, por meio das várias formas de manifestação da arte." />
<meta name="google:title" content="Oficial | Torneio Intercolegial Tina Tune" />
<meta name="google:image" content="https://www.intercolegialtinatune.co.ao/web-files/images/logo_front.png" />
<!-- // SEO-->
<!--===============================================================================================-->
<!-- Font Awesome -->
<link rel="stylesheet" href="/intercolegial/web-files/adm/plugins/fontawesome-free/css/all.min.css">

<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- icheck bootstrap -->
<link rel="stylesheet" href="https://www.intercolegialtinatune.co.ao/web-files/adm/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="https://www.intercolegialtinatune.co.ao/web-files/adm/dist/css/adminlte.min.css">
<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

<!-- ========== Favicon Ico ========== -->
<link rel="icon" href="https://www.intercolegialtinatune.co.ao/web-files/images/icon.png" type="image/ico" />