<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="pt">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?= $v_title_page?></title>
    <?php
    include_once 'app/views/public/head-login.phtml';
    ?>
</head>

<body class="bg-login">


    <div class="sufee-login d-flex align-content-center flex-wrap">
        <div class="container">
            <div class="login-content">
                <div class="login-logo">
                    <a href="/autenticador/Login/index">
                        <img class="align-content" src="/autenticador/web-files/images/logo.png" alt="">
                    </a>
                </div>
                <div class="login-form">
                    <form action="#" method="post">
                        <div class="form-group">
                            <label>Email</label>
                            <input type="email" class="form-control" required placeholder="Seu Email de segurança">
                        </div>
                            <button type="submit" class="btn btn-primary btn-flat m-b-15">Enviar</button>

                    </form>
                </div>
            </div>
        </div>
    </div>

    <?php
    include_once 'app/views/public/foot-login.phtml';
    ?>
</body>
</html>
