<!DOCTYPE html>
<html lang="pt">

<?php
include_once 'app/views/public/head.phtml';
include_once 'app/views/public/adm/selectorCSS.phtml';
?>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">


	<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target" id="ftco-navbar">
		<div class="container">
			<!--<a class="navbar-brand" href="index.html">Meet<span>Up.</span></a>-->
			<a class="navbar-brand" href="https://www.intercolegialtinatune.co.ao/Home/"><img src="https://www.intercolegialtinatune.co.ao/web-files/images/logo_front.png" style="width: 30%;"></span></a>
			<button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="oi oi-menu"></span> Menu
			</button>

			<div class="collapse navbar-collapse" id="ftco-nav">
				<ul class="navbar-nav nav ml-auto">
					<li class="nav-item"><a href="../#home-section" class="nav-link"><span>Início</span></a></li>
					<li class="nav-item"><a href="../#about-section" class="nav-link"><span>Torneio intercolegial</span></a></li>
					<li class="nav-item"><a href="../#schedule-section" class="nav-link"><span>Calendário</span></a></li>
					<li class="nav-item"><a href="../#blog-section" class="nav-link"><span>Novidades</span></a></li>
					<li class="nav-item"><a href="../#contact-section" class="nav-link"><span>Contactos</span></a></li>
					<li class="nav-item cta"><a href="#" data-toggle="modal" data-target="#inscricaoModal" class="nav-link">Inscrever-se</a></li>
				</ul>
			</div>
		</div>
	</nav>
	<section class="hero-wrap hero-wrap-2" style="background-image: url('https://www.intercolegialtinatune.co.ao/web-files/images/bg_2.jpg');">
		<div class="overlay"></div>
		<div class="container">
			<div class="row no-gutters slider-text align-items-end justify-content-center">
				<div class="col-md-9 ftco-animate pb-5 text-center">
					<h1 class="mb-3 bread" style="color: #ff0000;">Página de erro</h1>
				</div>
			</div>
		</div>
	</section>


	<section class="ftco-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 ftco-animate">
					<h2 class="mb-3" style="color: #ff0000;">
						<?php
						if (isset($v_mensagem)) {
							echo $v_mensagem;
						} else {
						?>
							A página que solicitou não existe ou não tem permissão para visualizar esta informação.
						<?php
						}
						?>
               </h2>
               <a style="cursor:pointer" onclick="voltar();" class="btn btn-primary" title="Voltar"><i class="fa fa-chevron-left"></i><strong> Voltar</strong></a>

				</div> <!-- .col-md-8 -->

			</div>
		</div>
	</section> <!-- .section -->

	<!-- Footer -->
	<footer class="ftco-footer ftco-section">
		<div class="container">
			<div class="row mb-5">
				<div class="col-md">
					<div class="ftco-footer-widget mb-4">
						<!--<h2 class="ftco-heading-2">Realização</h2>-->
						<div class="">
							<img src="https://www.jam.co.ao/web-files/assets/img/logo.png" alt="JAM">
						</div>
						<p></p>
						<ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
							<li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
							<li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
							<li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
						</ul>
					</div>
				</div>
				<div class="col-md">
					<div class="ftco-footer-widget mb-4 ml-md-4">
						<h2 class="ftco-heading-2">Mapa</h2>
						<ul class="list-unstyled">
							<li><a href="../#home-section"><span class="icon-long-arrow-right mr-2"></span>Início</a></li>
							<li><a href="../#about-section"><span class="icon-long-arrow-right mr-2"></span>Torneio intercolegial</a></li>
							<li><a href="../#schedule-section"><span class="icon-long-arrow-right mr-2"></span>Calendário</a></li>
							<li><a href="../#blog-section"><span class="icon-long-arrow-right mr-2"></span>Novidades</a></li>
							<li><a href="../#contact-section"><span class="icon-long-arrow-right mr-2"></span>Contactos</a></li>
						</ul>
					</div>
				</div>
				<div class="col-md">
					<div class="ftco-footer-widget mb-4">
						<h2 class="ftco-heading-2">Conta</h2>
						<ul class="list-unstyled">
							<li><a href="https://www.intercolegialtinatune.co.ao/Login/" target="blank"><span class="icon-long-arrow-right mr-2"></span>Entrar</a></li>
							<li><a href="#inscricao" data-toggle="modal" data-target="#inscricaoModal"><span class="icon-long-arrow-right mr-2"></span>Inscrever-se</a></li>
						</ul>
					</div>
				</div>
				<div class="col-md">
					<div class="ftco-footer-widget mb-4">
						<h2 class="ftco-heading-2">Alguma dúvida?</h2>
						<div class="block-23 mb-3">
							<ul>
								<li><span class="icon icon-map-marker"></span><span class="text">Estrada do Patriota, Edif. Kissange, 1º Andar A</span></li>
								<li><a href="#"><span class="icon icon-phone"></span><span class="text">+244 931 199 396</span></a></li>
								<li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@intercolegialtinatune.co.ao</span></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 text-center">

					<p>
						<?php echo date('Y'); ?> &copy; JAM ENT &bull; <a href="https://mrvipaji.ao/" target="new">MRVIPAJI - Quizá, el mejor del mundo</a>
					</p>
				</div>
			</div>
		</div>
	</footer>
	<!-- // Footer -->

	<!-- loader -->
	<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
			<circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
			<circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>

	<?php
	include_once 'app/views/public/modal/inscricao.phtml';
	include_once 'app/views/public/javascript.phtml';
	include_once 'app/views/public/adm/selectorJS.phtml';
	?>

</body>

</html>