    
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <!--<link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">-->
    <link rel="icon" href="/autenticador/web-files/img/logo.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="/autenticador/web-files/css/bootstrap.min.css">
    <link rel="stylesheet" href="/autenticador/web-files/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/autenticador/web-files/css/magnific-popup.css">
    <link rel="stylesheet" href="/autenticador/web-files/css/font-awesome.min.css">
    <link rel="stylesheet" href="/autenticador/web-files/css/themify-icons.css">
    <link rel="stylesheet" href="/autenticador/web-files/css/nice-select.css">
    <link rel="stylesheet" href="/autenticador/web-files/css/flaticon.css">
    <link rel="stylesheet" href="/autenticador/web-files/css/animate.css">
    <link rel="stylesheet" href="/autenticador/web-files/css/slicknav.css">
    <link rel="stylesheet" href="/autenticador/web-files/css/style.css">
    <!-- <link rel="stylesheet" href="/autenticador/web-files/css/responsive.css"> -->