<footer class="footer footer_bg">
        <div class="footer_top">
            <div class="container-fluid p-0">
                <div class="row no-gutters ">
                    <div class="col-xl-3 col-12 col-md-4">
                        <div class="footer_widget">
                            <div class="footer_logo">
                                <a href="index">
                                    <img src="/autenticador/web-files/img/logo.png" style="width: 50%;" alt="">
                                </a>
                            </div>
                            <ul class="social_links">
                                <li>
                                    <a href="https://www.facebook.com/camaraangola.eau" target="blank"><i class="fa fa-facebook"></i></a>
                                </li>
                                
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-9 col-12 col-md-8">
                        <div class="row">
                            <div class="col-xl-8 col-12 col-md-12">
                                <div class="row">
                                    <div class="col-xl-4 col-12 col-md-4">
                                        <div class="footer_widget">
                                            <h3 class="footer_heading">
                                                Navegação
                                            </h3>
                                            <ul class="quick_links">
                                                <li><a href="/autenticador/home/index">Início</a></li>
                                                <li><a href="/autenticador/home/acerca"> Sobre nós</a></li>
                                                <li><a href="#"> Actividades</a></li>
                                                <li><a href="/autenticador/home/galeria"> Galeria</a></li>
                                                <!--
                                                <li><a href="#">Services</a></li>
                                                <li><a href="#">Blog</a></li>
                                                -->
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-xl-4 col-12 col-md-4">
                                        <div class="footer_widget">
                                            <h3 class="footer_heading">
                                                Serviço
                                            </h3>
                                            <ul class="quick_links">
                                                <li><a href="#">Registar empresa</a></li>
                                                <!--
                                                <li><a href="#"> Exterior</a></li>
                                                <li><a href="#"> Bridge</a></li>
                                                -->
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-xl-4 col-12 col-md-4 ">
                                        <div class="footer_widget">
                                            <h3 class="footer_heading">
                                                Contactar
                                            </h3>
                                            <ul class="quick_links">
                                                <li><a href="callto:+244924939498"><span class="fa fa-phone"></span> +244 924 939 498</a></li>
                                                <li><a href="#"><span class="fa fa-whatsapp"></span> +244 928 885 330</a></li>
                                                <li><a href="mailto:geral@angoeauchamber.com">geral@angoeauchamber.com</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer_copy_right">
            <p>CCVF &copy;<script>document.write(new Date().getFullYear());</script> Todos direitos reservados</p>
        </div>
    </footer>