<header>
        <div class="header-area">
            <div id="sticky-header" class="main-header-area white-bg">
                <div class="container-fluid p-0">
                    <div class="row align-items-center justify-content-between no-gutters">
                        <div class="col-xl-2 col-lg-2">
                            <div class="logo-img">
                                <a href="/autenticador/home/index">
                                    <img src="/autenticador/web-files/img/logo.png" alt="" style="width: 40%;">
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-7 col-lg-7">
                            <div class="main-menu d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a class="active" href="/autenticador/home/index" style="font-size: 19px;">Início</a></li>
                                        <li><a href="/autenticador/home/acerca" style="font-size: 19px;">Sobre nós</a></li>
                                        <!--<li><a href="project.html">Actividades</a></li>-->
                                        <li><a href="#" style="font-size: 19px;">Serviço <i class="ti-angle-down"></i></a>
                                            <ul class="submenu">
                                                <li><a href="#" style="font-size: 19px;">Registar empresa</a></li>
                                                <!--<li><a href="single-blog.html">single-blog</a></li>-->
                                            </ul>
                                        </li>
                                        <li><a href="/autenticador/home/galeria" style="font-size: 19px;">Galeria</a></li>
                                        <li><a href="/autenticador/home/contacto" style="font-size: 19px;">Contactos</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                           <div class="get_in_tauch">
                                <a href="callto:+244924939498" class="boxed-btn"><span class="fa fa-phone"></span> 924939498</a>
                            </div>
                       </div>
                        
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>