    <script src="/autenticador/web-files/js/vendor/modernizr-3.5.0.min.js"></script>
    <script src="/autenticador/web-files/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="/autenticador/web-files/js/popper.min.js"></script>
    <script src="/autenticador/web-files/js/bootstrap.min.js"></script>
    <script src="/autenticador/web-files/js/owl.carousel.min.js"></script>
    <script src="/autenticador/web-files/js/isotope.pkgd.min.js"></script>
    <script src="/autenticador/web-files/js/ajax-form.js"></script>
    <script src="/autenticador/web-files/js/waypoints.min.js"></script>
    <script src="/autenticador/web-files/js/jquery.counterup.min.js"></script>
    <script src="/autenticador/web-files/js/imagesloaded.pkgd.min.js"></script>
    <script src="/autenticador/web-files/js/scrollIt.js"></script>
    <script src="/autenticador/web-files/js/jquery.scrollUp.min.js"></script>
    <script src="/autenticador/web-files/js/wow.min.js"></script>
    <script src="/autenticador/web-files/js/nice-select.min.js"></script>
    <script src="/autenticador/web-files/js/jquery.slicknav.min.js"></script>
    <script src="/autenticador/web-files/js/jquery.magnific-popup.min.js"></script>
    <script src="/autenticador/web-files/js/plugins.js"></script>

    <!--contact js-->
    <script src="/autenticador/web-files/js/contact.js"></script>
    <script src="/autenticador/web-files/js/jquery.ajaxchimp.min.js"></script>
    <script src="/autenticador/web-files/js/jquery.form.js"></script>
    <script src="/autenticador/web-files/js/jquery.validate.min.js"></script>
    <script src="/autenticador/web-files/js/mail-script.js"></script>

    <script src="/autenticador/web-files/js/main.js"></script>