<div class="drop-men" >
		        <ul class=" nav_1">
		           
		    		<li class="dropdown at-drop">
		              <a href="#" class="dropdown-toggle dropdown-at " data-toggle="dropdown"><i class="fa fa-globe"></i> <span class="number">5</span></a>
		              <ul class="dropdown-menu menu1 " role="menu">
		                <li><a href="#">
		               
		                	<div class="user-new">
		                	<p>Recente</p>
		                	<span>Há 40 segundos</span>
		                	</div>
		                	<div class="user-new-left">
		                
		                	<i class="fa fa-user-plus"></i>
		                	</div>
		                	<div class="clearfix"> </div>
		                	</a></li>
		              </ul>
		            </li>
					<li class="dropdown">
		              <a href="#" class="dropdown-toggle dropdown-at" data-toggle="dropdown"><span class=" name-caret">
					  <?php
						if(isset($v_userInfo))
						{
                            echo $v_userInfo->getNome();
                        }
                        ?>
						  <i class="caret"></i></span><img src="/autenticador/web-files/adm/images/wo.jpg"></a>
		              <ul class="dropdown-menu " role="menu">
		                <!--<li><a href="#"><i class="fa fa-user"></i>Editar Perfi</a></li>-->
		                <li><a href="/autenticador/Login/logout"><i class="fa fa-sign-out"></i>Sair</a></li>
		              </ul>
		            </li>
		           
		        </ul>
		     </div>