<div class=" border-bottom">
	<div class="full-left">
	<!--<section class="full-top">
		<button id="toggle">
			<i class="fa fa-arrows-alt"></i>
		</button>
    </section>-->
	<form class=" navbar-left-right" action="/autenticador/Publicacao/pesquisar" method="POST">
		<input type="text" name="chave"  value="Pesquisar..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search...';}">
		<input type="submit" value="" class="fa fa-search">
	</form>
	<div class="clearfix"></div>
</div>