<div class="slider_area">
        <div class="slider_active owl-carousel">
            <div class="single_slider overlay2 d-flex align-items-center justify-content-center slider_bg_1">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="slider_text text-center">
                                <!--
                                <h3>Câmara do Comércio Angola & EAU</h3>
                                <p>Auxilio em Assuntos na busca de investiores nos Emirados Arabes Unidos com interesse de procurar parceiros em Angola.</p>
                                <a href="#" class="boxed-btn2">Saiba mais</a>
                                -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="single_slider overlay2 d-flex align-items-center justify-content-center slider_bg_2">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="slider_text text-center">
                                <!--
                                <h3>Câmara do Comércio Angola & EAU</h3>
                                <p>Auxilio em Assuntos na busca de investiores nos Emirados Arabes Unidos com interesse de procurar parceiros em Angola.</p>
                                <a href="#" class="boxed-btn2">Saiba mais</a>
                                -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="single_slider overlay2 d-flex align-items-center justify-content-center slider_bg_3">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="slider_text text-center">
                                <!--
                                <h3>Câmara do Comércio Angola & EAU</h3>
                                <p>Auxilio em Assuntos na busca de investiores nos Emirados Arabes Unidos com interesse de procurar parceiros em Angola.</p>
                                <a href="#" class="boxed-btn2">Saiba mais</a>
                                -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="single_slider overlay2 d-flex align-items-center justify-content-center slider_bg_4">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="slider_text text-center">
                                <!--
                                <h3>Câmara do Comércio Angola & EAU</h3>
                                <p>Auxilio em Assuntos na busca de investiores nos Emirados Arabes Unidos com interesse de procurar parceiros em Angola.</p>
                                <a href="#" class="boxed-btn2">Saiba mais</a>
                                -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="single_slider overlay2 d-flex align-items-center justify-content-center slider_bg_5">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="slider_text text-center">
                                <!--
                                <h3>Câmara do Comércio Angola & EAU</h3>
                                <p>Auxilio em Assuntos na busca de investiores nos Emirados Arabes Unidos com interesse de procurar parceiros em Angola.</p>
                                <a href="#" class="boxed-btn2">Saiba mais</a>
                                -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>