<nav class="mt-2">
  <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
    <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
    <li class="nav-item has-treeview menu-open">
      <a href="#" class="nav-link active">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>
          Dashboard
          <i class="right "></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="https://www.intercolegialtinatune.co.ao/Dashboard/" class="nav-link active">
            <i class="far fa-circle nav-icon"></i>
            <p>Principal</p>
          </a>
        </li>
      </ul>
    </li>
    
    <li class="nav-header">GESTÃO</li>
    <li class="nav-item">
      <a href="https://www.intercolegialtinatune.co.ao/Estudante/" class="nav-link">
        <i class="nav-icon fas fa-users"></i>
        <p>
          Estudantes
        </p>
      </a>
    </li>
    <li class="nav-item">
      <a href="https://www.intercolegialtinatune.co.ao/Evento/" class="nav-link">
        <i class="nav-icon far fa-calendar-alt"></i>
        <p>
          Eventos
        </p>
      </a>
    </li>
    <li class="nav-item">
      <a href="https://www.intercolegialtinatune.co.ao/Escola/" class="nav-link">
        <i class="nav-icon fas fa-school"></i>
        <p>
          Escolas
        </p>
      </a>
    </li>
    <li class="nav-item">
      <a href="https://www.intercolegialtinatune.co.ao/Blog/" class="nav-link">
        <i class="nav-icon fas fa-microphone"></i>
        <p>
          Novidades
        </p>
      </a>
    </li>
    <li class="nav-item">
      <a href="https://www.intercolegialtinatune.co.ao/Utilizador/" class="nav-link">
        <i class="nav-icon fas fa-user"></i>
        <p>
          Utilizadores
        </p>
      </a>
    </li>
    
    <li class="nav-header">DEFINIÇÕES</li>
    <li class="nav-item has-treeview">
      <a href="#" class="nav-link">
        <i class="nav-icon fas fa-users"></i>
        <p>
          Utilizadores
          <i class="fas fa-angle-left right"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="https://www.intercolegialtinatune.co.ao/Perfil/" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Perfil</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="https://www.intercolegialtinatune.co.ao/Permissao/" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Permissões</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="https://www.intercolegialtinatune.co.ao/Log/" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Actividades</p>
          </a>
        </li>
      </ul>
    </li>

    <li class="nav-item has-treeview">
      <a href="#" class="nav-link">
        <i class="nav-icon fas fa-school"></i>
        <p>
          Escola
          <i class="fas fa-angle-left right"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <!--<li class="nav-item">
          <a href="https://www.intercolegialtinatune.co.ao/Categoria/" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Categorias</p>
          </a>
        </li>-->
        <li class="nav-item">
          <a href="https://www.intercolegialtinatune.co.ao/TipoEscola/" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Tipo</p>
          </a>
        </li>
        <!--<li class="nav-item">
          <a href="https://www.intercolegialtinatune.co.ao/Marca/" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Marcas</p>
          </a>
        </li>-->
      </ul>
    </li>
  </ul>
</nav>