<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title><?= $v_title_page;?></title>

  <?php
    include_once 'app/views/public/adm/head.phtml';
  ?>
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
  <div class="wrapper">
    <!-- Navbar -->
    <?php
      include_once 'app/views/public/adm/topNavigation.phtml';
    ?>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar elevation-4 sidebar-light-warning">
      <!-- Brand Logo -->
      <?php
        include_once 'app/views/public/adm/logo.phtml';
      ?>
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <?php
        include_once 'app/views/public/adm/userInfo.phtml';
        ?>
        <!-- Sidebar Menu -->
        <?php
        include_once 'app/views/public/menuLateral.phtml';
        ?>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Perfil de Utilizador</h1>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- Main row -->
          <div class="row">
            <!-- / Corpo da página INÍCIO -->
            <div class="col-md-3">

              <!-- Profile Image -->
              <div class="card card-orange card-outline">
                <div class="card-body box-profile">
                  <div class="text-center">
                    <?php
                        if (isset($v_entity)) {
                            $foto = $v_entity->getFoto();
                            if (!$v_entity->getFoto() == null) {
                                echo '<img class="profile-user-img img-fluid img-circle" src="' . Geral::DIR_IMG_UTILIZADORES . $foto . '" alt="Foto de ' . $v_entity->getNome() . '" title="Foto de ' . $v_entity->getNome() . '" />';
                                } else {
                                    echo '<img class="profile-user-img img-fluid img-circle" src="/web-files/default/m.jpg" alt="Foto de ' . $v_entity->getNome() . '">';
                                }
                            }
                    ?>
                  </div>

                  <h3 class="profile-username text-center"><?= $v_entity->getNome(); ?></h3>
                  <p class="text-muted text-center"><?= ucfirst(Method::lowerGeneral($v_entity->getPerfil()->getNome())); ?></p>
                  <p class="text-center"><?= $v_entity->getEmail(); ?></p>
                  <a data-toggle="modal" class="btn btn-primary btn-block" data-target="#alterarfoto" style="cursor:pointer;"><i class="fa fa-photo m-right-xs"></i> Adicionar foto</a>                          
                  <a class="btn btn-secondary btn-block" data-toggle="modal" data-target="#alterarpassword"  style="cursor:pointer;"><i class="fa fa-lock m-right-xs"></i> Alterar Palavra-passe</a>
                                        
                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
            </div>
            <?php
            include_once 'app/views/utilizador/tabuladores/tab-log.phtml';
            ?>
            <!-- / Corpo da página FIM -->
          </div>
          <!-- /.row -->
        </div>
        <!--/. container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
    <!-- Modal-password-->
    <?php
        include_once 'app/views/utilizador/modal/modal-password.phtml';
        include_once 'app/views/utilizador/modal/modal-add-foto.phtml';
    ?>
        <!-- // Modal - Adicionar Foto -->
    <!-- Main Footer -->
    <?php
    include_once 'app/views/public/adm/foot.phtml';
    ?>

  </div>
  <!-- ./wrapper -->

  <?php
    include_once 'app/views/public/adm/javascript.phtml';
    include_once 'app/views/public/adm/datatables.phtml';
  ?>
</body>

</html>