<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title><?= $v_title_page;?></title>

  <?php
    include_once 'app/views/public/adm/head.phtml';
  ?>
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
  <div class="wrapper">
    <!-- Navbar -->
    <?php
      include_once 'app/views/public/adm/topNavigation.phtml';
    ?>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar elevation-4 sidebar-light-warning">
      <!-- Brand Logo -->
      <?php
        include_once 'app/views/public/adm/logo.phtml';
      ?>
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <?php
        include_once 'app/views/public/adm/userInfo.phtml';
        ?>
        <!-- Sidebar Menu -->
        <?php
        include_once 'app/views/public/menuLateral.phtml';
        ?>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark"><?= $v_page_context;?></h1>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- Main row -->
          <div class="row">
            <!-- / Corpo da página INÍCIO -->

            <div class="col-6">
              <div class="card">

              <form role="form" id="formPerfil" method="POST" action="<?= $v_page_url;?>actualizar">
                <div class="card-body">
                  <div class="form-group">
                    <label for="nome-<?= $v_page_context;?>">Nome</label>
                    <input type="text" name="nome" class="form-control" id="nome-<?= $v_page_context;?>" placeholder="Nome do <?= $v_page_context;?>" value="<?= $v_entity->getNome(); ?>">
                    <input type="hidden" name="id_utilizador" value="<?= $v_entity->getId(); ?>"> 
                  </div>
                  <div class="form-group">
                    <label for="email-<?= $v_page_context;?>">E-mail</label>
                    <input type="email" name="email" class="form-control" id="email-<?= $v_page_context;?>" placeholder="Email do <?= $v_page_context;?>"  value="<?= $v_entity->getEmail(); ?>">
                  </div>
                    <?php
                    if (Method::lowerGeneral($v_userInfo->getPerfil()->getNome()) == Geral::CONS_PERFIL_ADMINISTRADOR)
                    {
                    ?>
                    <div class="form-group">
                    <label for="email-<?= $v_page_context;?>">Palavra-passe</label><br>
                      <a href="<?= $v_page_url ?>redifinir/<?php echo base64_encode("id") . '/' . base64_encode($v_entity->getId()) ?>" class="btn btn-info btn-circle" title="Redifinir"><i class="fa fa-refresh"></i> Redifinir Palavra-passe</a>
                    </div>
                    <?php
                    }
                    ?>
                  <div class="form-group">
                    <label for="perfil-<?= $v_page_context;?>">Perfil</label>
                    <select id="perfil-<?= $v_page_context;?>" name="perfil" class="form-control" required="" >
                    <?php
                      $v_perfis = (isset($v_perfis) ? ($v_perfis) : (array()));
                        foreach ($v_perfis as $perfil) {
                          echo '<option value="' . $perfil->getId() . '" ' . ($perfil->getId() == $v_entity->getPerfil()->getId() ? 'selected' : '') . '>' . ucfirst(Method::lowerGeneral($perfil->getNome())) . '</option> ';
                        }
                    ?>
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="estado-<?= $v_page_context;?>">Estado</label>
                    <select id="estado-<?= $v_page_context;?>" name ="estado" class="form-control" required="" >
                      <?php
                        echo '<option value="' . Geral::CONS_UTILIZADOR_ACTIVADO . '" ' . (Geral::CONS_UTILIZADOR_ACTIVADO == $v_entity->getEstado() ? 'selected' : '') . '>Activado</option> ';
                        echo '<option value="' . Geral::CONS_UTILIZADOR_DESACTIVADO . '" ' . (Geral::CONS_UTILIZADOR_DESACTIVADO == $v_entity->getEstado() ? 'selected' : '') . '>Desactivado</option> ';
                      ?>
                    </select>
                  </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                <a href="<?=$v_page_url ?>" class="btn btn-default btn-circle" title="Voltar"><i
                        class="fa fa-chevron-left"></i><strong> Voltar</strong></a>
                        <button type="submit" class="btn btn-primary">Actualizar <?= $v_page_context;?></button>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                    
                  </div>
                </div>
              </form>
              </div>
            </div>
            <!-- / Corpo da página FIM -->
          </div>
          <!-- /.row -->
        </div>
        <!--/. container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <?php
    include_once 'app/views/public/adm/foot.phtml';
    ?>

  </div>
  <!-- ./wrapper -->

  <?php
    include_once 'app/views/public/adm/javascript.phtml';
    include_once 'app/views/public/adm/datatables.phtml';
  ?>
</body>
</html>