<?php
include_once 'app/views/public/begin.phtml';
echo ' <title>' . $v_title_page . '</title>';
include_once 'app/views/public/head.phtml';
include_once 'app/views/public/header.phtml';
?>

<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <div class="navbar nav_title" style="border: 0;">
                    <!-- logo quick info -->
                    <?php
                    include_once 'app/views/public/logo.phtml';
                    ?>
                    <!-- /logo quick info -->
                </div>

                <div class="clearfix"></div>

                <!-- menu profile quick info -->
                <?php
                include_once 'app/views/public/userInfo.phtml';
                ?>
                <!-- /menu profile quick info -->

                <br />

                <!-- sidebar menu -->
                <?php
                include_once 'app/views/public/menuLateral.phtml';
                ?>
                <!-- /sidebar menu -->

            </div>
        </div>

        <!-- top navigation -->
        <?php
        include_once 'app/views/public/topNavigation.phtml';
        ?>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
            <div class="">
                <div class="page-title">
                    <div class="title_left">
                        <h3><i class="<?= $v_page_icon ?>"></i>&nbsp;<?= $v_page_context ?>  <small> Novo</small></h3>
                    </div>

                    <div class="title_right">
                        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                            <div class="input-group">
                                <span class="input-group-btn">
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h4 ><i class="fa fa-plus"></i> Registar  <span style="padding-left: 1%; font-size: 12px; color: black; "> <strong>Nota: </strong>Os campos com
                                        <span style="color: red;"> *</span> são obrigatórios 
                                    </span> 
                                </h4>
                                <div class="clearfix"></div>
                            </div>

                            <div class="x_content">

                                <form id="demo-form" class="form-horizontal form-label-left" data-parsley-validate="" novalidate="" method="POST" action="<?= $v_page_url ?>registar" enctype="multipart/form-data">

                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nome">Nome: <span style="color: red;"> *</span> 
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="text" name="nome" id="nome" required="required" class="form-control col-md-7 col-xs-12">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="descricao">Descrição: <span style="color: red;"> *</span> 
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="text" name="descricao" id="descricao" required="required" class="form-control col-md-7 col-xs-12">
                                        </div>
                                    </div>

                                    <div class="ln_solid"></div>
                                    <div class="form-group">
                                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                            <a  onclick="Voltar();" class="btn btn-default btn-circle" title="Voltar"><i class="fa fa-chevron-left"></i><strong> Voltar</strong></a> 
                                            <button class="btn btn-default" type="reset">Limpar</button>
                                            <button type="submit" class="btn btn-success">Gravar</button>
                                        </div>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /page content -->

        <?php
        include_once 'app/views/public/footer.phtml';
        include_once 'app/views/public/javascript.phtml';
        ?>
        <script src="/Muxima_Helpdesk/web-files/default/js/validacao/parsley.js"></script>
        <script src="/Muxima_Helpdesk/web-files/default/js/validacao/pt-pt.js"></script>
        <?php
        include_once 'app/views/public/end.phtml';
        ?>