
<!-- Modal -->
<div class="modal fade" id="editarUtilizador" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="exampleModalLongTitle"><i class="fas fa-user-plus"></i> Editar utilizador</h4>
                
            </div>
            <div class="modal-body">

             

                <form id="demo-form" autocomplete="off" class="form-horizontal form-label-left" data-parsley-validate="" novalidate="" method="POST" action="<?= $v_page_url ?>actualizar" enctype="multipart/form-data">


                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="">Nome: <span style="color: red;"> *</span> 
                        </label>
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <input type="text" name ="nome" id="nome" required="" value="<?= ucfirst($v_entity->getNome()); ?>" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="">E-mail: <span style="color: red;"> *</span> 
                        </label>
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <input type="email" name="email" id="email" required="" value="<?= $v_entity->getEmail(); ?>" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="">Telefone: <span style="color: red;"> *</span> 
                        </label>
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <input type="text" name="telefone" id="telefone" required="" value="<?= ucfirst($v_entity->getTelefone()); ?>" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="funcao_utilizador">Função: <span style="color: red;"> *</span> 
                        </label>
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <select id="funcao"  name ="funcao" class="form-control selectpicker" data-show-subtext="true"  data-live-search="true" required="">

                                <?php
                                $v_funcoes = (isset($v_funcoes) ? ($v_funcoes) : (array()));
                                foreach ($v_funcoes as $funcao) {
                                    echo '<option value="' . $funcao->getId() . '" ' . ($funcao->getId() == $v_entity->getFuncao()->getId() ? 'selected' : '') . '>' . ucfirst($funcao->getNome()) . '</option> ';
                                }
                                ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="funcao_utilizador">Estado: <span style="color: red;"> *</span> 
                        </label>
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <select id="estado"  name ="estado" class="form-control" required="">
                                <?php
                                echo '<option value="' . Geral::CONS_UTILIZADOR_ACTIVADO . '" ' . (Geral::CONS_UTILIZADOR_ACTIVADO == $v_entity->getEstado() ? 'selected' : '') . '>' . "Activo" . '</option> ';
                                echo '<option value="' . Geral::CONS_UTILIZADOR_DESACTIVADO . '" ' . (Geral::CONS_UTILIZADOR_DESACTIVADO == $v_entity->getEstado() ? 'selected' : '') . '>' . "Inactivo" . '</option> ';
                                ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="">Empresa: <span style="color: red;"> *</span> 
                        </label>
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <select id="empresa"  name ="empresa" class="form-control selectpicker" data-show-subtext="true"  data-live-search="true" required="">

                                <?php
                                if ($v_entity->getEmpresa() == null) {
                                    $v_empresas = (isset($v_empresas) ? ($v_empresas) : (array()));
                                    echo '<option value="" selected></option> ';
                                    foreach ($v_empresas as $v_empresa) {
                                        echo '<option value="' . $v_empresa->getId() . '">' . ucfirst($v_empresa->getNome()) . '</option> ';
                                    }
                                } else {
                                    $v_empresas = (isset($v_empresas) ? ($v_empresas) : (array()));
                                    foreach ($v_empresas as $v_empresa) {
                                        echo '<option value="' . $v_empresa->getId() . '" ' . ($v_empresa->getId() == $v_entity->getEmpresa()->getId() ? 'selected' : '') . '>' . ucfirst($v_empresa->getNome()) . '</option> ';
                                    }
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="">Departamento: <span style="color: red;"> *</span> 
                        </label>
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <select id="departamento"  name ="departamento" class="form-control selectpicker" data-show-subtext="true"  data-live-search="true" required="">
                                <?php
                                if ($v_entity->getDepartamento() == null) {
                                    $v_departamentos = (isset($v_departamentos) ? ($v_departamentos) : (array()));
                                    echo '<option value="" selected></option> ';
                                    foreach ($v_departamentos as $v_departamento) {
                                        echo '<option value="' . $v_departamento->getId() . '">' . ucfirst($v_departamento->getNome()) . '</option> ';
                                    }
                                } else {
                                    $v_departamentos = (isset($v_departamentos) ? ($v_departamentos) : (array()));
                                    foreach ($v_departamentos as $v_departamento) {
                                        echo '<option value="' . $v_departamento->getId() . '" ' . ($v_departamento->getId() == $v_entity->getDepartamento()->getId() ? 'selected' : '') . '>' . ucfirst($v_departamento->getNome()) . '</option> ';
                                    }
                                }
                                ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="">Cargo: <span style="color: red;"> *</span> 
                        </label>
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <select id="cargo"  name ="cargo" class="form-control selectpicker" data-show-subtext="true"  data-live-search="true" required="">
                                <?php
                                if ($v_entity->getCargo() == null) {
                                    $v_cargos = (isset($v_cargos) ? ($v_cargos) : (array()));
                                    echo '<option value="" selected></option> ';
                                    foreach ($v_cargos as $v_cargo) {
                                        echo '<option value="' . $v_cargo->getId() . '">' . ucfirst($v_cargo->getNome()) . '</option> ';
                                    }
                                } else {
                                    $v_cargos = (isset($v_cargos) ? ($v_cargos) : (array()));
                                    foreach ($v_cargos as $v_cargo) {
                                        echo '<option value="' . $v_cargo->getId() . '" ' . ($v_cargo->getId() == $v_entity->getCargo()->getId() ? 'selected' : '') . '>' . ucfirst($v_cargo->getNome()) . '</option> ';
                                    }
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                    <input type="hidden" id="custId" name="id_utilizador" value="<?= $v_entity->getId(); ?>">


                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Gravar</button>
                            <button class="btn btn-default" type="reset"><i class="fa fa-eraser"></i> Limpar</button>
                        </div>
                    </div>
                </form>

            </div>

        </div>

    </div>
</div>

<!-- // Modal -->



