<div class="modal fade" id="alterarpassword" tabindex="-1" role="dialog" aria-labelledby="alterarpasswordTitulo" aria-hidden="true" data-backdrop="static">
            <div class="modal-dialog" role="document">
                <form action="<?= $v_page_url ?>password" method="post">

                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLongTitle"><i class="fa fa-lock fa-1x"></i> Alterar sua palavra-passe</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">

                            <style>
                                /* The message box is shown when the user clicks on the password field */
                                #message {
                                    display:none;
                                    background: #f1f1f1;
                                    color: #000;
                                    position: relative;
                                    padding: 20px;
                                    margin-top: 10px;
                                }

                                #message p {
                                    padding: 10px 35px;
                                    font-size: 18px;
                                }

                                /* Add a green text color and a checkmark when the requirements are right */
                                .valido {
                                    color: green;
                                }

                                .valido:before {
                                    position: relative;
                                    left: -35px;
                                    content: "✔";
                                }

                                /* Add a red text color and an "x" when the requirements are wrong */
                                .invalido {
                                    color: red;
                                }

                                .invalido:before {
                                    position: relative;
                                    left: -35px;
                                    content: "✖";
                                }
                            </style>

                            <div class="form-group">
                                <label class="control-label col-md-12 col-sm-12 col-xs-12" for="actual">Palavra-passe actual: <span style="color: red;"> </span></label>
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <input type="password" id="password_actual" name="password_actual" required class="form-control col-md-12 col-xs-12" placeholder="Palavra-passe actual">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-12 col-sm-12 col-xs-12" for="new">Nova palavra-passe: <span style="color: red;"> </span></label>
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <input type="password" id="new" name="new" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Deve conter pelo menos um número e uma letra maiúscula e minúscula e pelo menos 8 ou mais caracteres" required class="form-control col-md-12 col-xs-12" placeholder="Nova palavra-passe">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-12 col-sm-12 col-xs-12" for="password_utilizador">Confirmação da palavra-passe: <span style="color: red;"> </span></label>
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <input type="password" id="password_utilizador" name="password_utilizador" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Deve conter pelo menos um número e uma letra maiúscula e minúscula e pelo menos 8 ou mais caracteres" required class="form-control col-md-12 col-xs-12" placeholder="Confirmação da palavra-passe">
                                    <input type="hidden" value="<?= $v_entity->getId(); ?>" name="id_utilizador">
                                </div>
                            </div>
                            <hr>
                            <div id="message">
                                <!--<h4>A palavra-passe deve conter o seguinte:</h4>-->
                                <p id="letter" class="invalido">Uma letra <b>minúscula</b>.</p>
                                <p id="capital" class="invalido">Uma letra <b>maiúscula</b>.</p>
                                <p id="number" class="invalido">Um <b>número</b></p>
                                <p id="length" class="invalido">Mínimo de <b>8 caracteres.</b></p>
                                <p id="equal" class="invalido">A confirmação da palavra-passe <b>coincide.</b></p>
                            </div>
                            <script>
                                var nova = document.getElementById("new");
                                var myInput = document.getElementById("password_utilizador");
                                var letter = document.getElementById("letter");
                                var capital = document.getElementById("capital");
                                var number = document.getElementById("number");
                                var length = document.getElementById("length");
                                var equal = document.getElementById("equal");

                                // When the user clicks on the password field, show the message box
                                myInput.onfocus = function () {
                                    document.getElementById("message").style.display = "block";
                                }

                                // When the user clicks outside of the password field, hide the message box
                                myInput.onblur = function () {
                                    document.getElementById("message").style.display = "none";
                                }

                                // When the user starts to type something inside the password field
                                myInput.onkeyup = function () {
                                    // Validate lowercase letters
                                    var lowerCaseLetters = /[a-z]/g;
                                    if (myInput.value.match(lowerCaseLetters)) {
                                        letter.classList.remove("invalido");
                                        letter.classList.add("valido");
                                    } else {
                                        letter.classList.remove("valido");
                                        letter.classList.add("invalido");
                                    }

                                    // Validate capital letters
                                    var upperCaseLetters = /[A-Z]/g;
                                    if (myInput.value.match(upperCaseLetters)) {
                                        capital.classList.remove("invalido");
                                        capital.classList.add("valido");
                                    } else {
                                        capital.classList.remove("valido");
                                        capital.classList.add("invalido");
                                    }

                                    // Validate numbers
                                    var numbers = /[0-9]/g;
                                    if (myInput.value.match(numbers)) {
                                        number.classList.remove("invalido");
                                        number.classList.add("valido");
                                    } else {
                                        number.classList.remove("valido");
                                        number.classList.add("invalido");
                                    }

                                    // Validate length
                                    if (myInput.value.length >= 8) {
                                        length.classList.remove("invalido");
                                        length.classList.add("valido");
                                    } else {
                                        length.classList.remove("valido");
                                        length.classList.add("invalido");
                                    }

                                    // confirmar se as confirmação da palavra-passe é igual
                                    if (nova.value == myInput.value) {
                                        equal.classList.remove("invalido");
                                        equal.classList.add("valido");
                                    } else {
                                        equal.classList.remove("valido");
                                        equal.classList.add("invalido");
                                    }
                                }
                            </script>

                        </div>
                        <div class="modal-footer">
                            <button type="submit" class=" btn btn-success">Gravar</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>