
<!-- Modal -->
<div class="modal fade" id="registarUtilizador" tabindex="-1" role="dialog" aria-labelledby="associarClienteTitulo" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="exampleModalLongTitle"><i class="fas fa-user-plus"></i> Registar utilizador</h4>
                
            </div>
            <div class="modal-body">

              

                <form id="demo-form" autocomplete="off" class="form-horizontal form-label-left" data-parsley-validate="" novalidate="" method="POST" action="<?= $v_page_url ?>registar" enctype="multipart/form-data">


                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="">Nome: <span style="color: red;"> *</span> 
                        </label>
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <input type="text" name ="nome" id="nome" required="" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="">E-mail: <span style="color: red;"> *</span> 
                        </label>
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <input type="email" name="email" id="email" required="" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="">Telefone: <span style="color: red;"> *</span> 
                        </label>
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <input type="text" name="telefone" id="telefone" required="" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="">Senha: <span style="color: red;"> *</span> 
                        </label>
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <input type="password" name="password" id="password" required="" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="funcao_utilizador">Função: <span style="color: red;"> *</span> 
                        </label>
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <select id="funcao"  name ="funcao" class="form-control" required="">
                                <option value="" selected="">---</option>
                                <?php
                                $v_funcoes = (isset($v_funcoes) ? ($v_funcoes) : (array()));
                                foreach ($v_funcoes as $funcao) {
                                    echo '<option value="' . $funcao->getId() . '">' . ucfirst(Method::lowerGeneral($funcao->getNome())) . '</option> ';
                                }
                                ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="">Empresa: <span style="color: red;"> *</span> 
                        </label>
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <select id="empresa"  name ="empresa" class="form-control selectpicker" data-show-subtext="true"  data-live-search="true" required="">
                                <option value="" selected=""></option>
                                <?php
                                $v_empresas = (isset($v_empresas) ? ($v_empresas) : (array()));
                                foreach ($v_empresas as $v_empresa) {
                                    echo '<option value="' . $v_empresa->getId() . '">' . ucfirst($v_empresa->getNome()) . '</option> ';
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="">Departamento: <span style="color: red;"> *</span> 
                        </label>
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <select id="departamento"  name ="departamento" class="form-control selectpicker" data-show-subtext="true"  data-live-search="true" required="">
                                <option value="" selected=""></option>
                                <?php
                                $v_departamentos = (isset($v_departamentos) ? ($v_departamentos) : (array()));
                                foreach ($v_departamentos as $v_departamento) {
                                    echo '<option value="' . $v_departamento->getId() . '">' . ucfirst($v_departamento->getNome()) . '</option> ';
                                }
                                ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="">Cargo: <span style="color: red;"> *</span> 
                        </label>
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <select id="cargo"  name ="cargo" class="form-control selectpicker" data-show-subtext="true"  data-live-search="true" required="">
                                <option value="" selected=""></option>
                                <?php
                                $v_cargos = (isset($v_cargos) ? ($v_cargos) : (array()));
                                foreach ($v_cargos as $v_cargo) {
                                    echo '<option value="' . $v_cargo->getId() . '">' . ucfirst($v_cargo->getNome()) . '</option> ';
                                }
                                ?>
                            </select>
                        </div>
                    </div>


                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button type="submit" class="btn btn-success" style="background-color: #6caa0d; border-color:#6caa0d; "><i class="fa fa-check"></i> Gravar</button>
                            <button class="btn btn-default" type="reset"><i class="fa fa-eraser"></i> Limpar</button>
                        </div>
                    </div>
                </form>

            </div>

        </div>

    </div>
</div>

<!-- // Modal -->



