<?php
include_once 'app/views/public/begin.phtml';
echo ' <title>' . $v_title_page . '</title>';
include_once 'app/views/public/head.phtml';
include_once 'app/views/public/header.phtml';
?>

<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <div class="navbar nav_title" style="border: 0;">
                    <!-- logo quick info -->
                    <?php
                    include_once 'app/views/public/logo.phtml';
                    ?>
                    <!-- /logo quick info -->
                </div>

                <div class="clearfix"></div>

                <!-- menu profile quick info -->
                <?php
                include_once 'app/views/public/userInfo.phtml';
                ?>
                <!-- /menu profile quick info -->

                <br />

                <!-- sidebar menu -->
                <?php
                include_once 'app/views/public/menuLateral.phtml';
                ?>
                <!-- /sidebar menu -->

            </div>
        </div>

        <!-- top navigation -->
        <?php
        include_once 'app/views/public/topNavigation.phtml';
        ?>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
            <div class="">
                <div class="page-title">
                    <div class="title_left">
                        <h3><i class="<?= $v_page_icon ?>"></i>&nbsp;<?= $v_page_context ?>  <small> Lista</small></h3>
                    </div>

                    <div class="title_right">
                        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                            <div class="input-group">
                              <!-- <input type="text" class="form-control" placeholder="Procurar por..."> -->
                                <span class="input-group-btn">
                                    <!-- <button class="btn btn-default" type="button">Encontrar</button> -->
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="x_panel">
                            <div class="x_title">

                                <?php
                                if (Method::lowerGeneral($v_userInfo->getFuncao()->getNome()) != Geral::CONS_PERFIL_COLABORADOR) {
                                    ?>
                                    <a href="#" class="btn btn-info btn-circle" title="Registar utilizador" data-toggle="modal" data-target="#registarUtilizador"><i class="fa fa-plus fa-1x"></i> Adicionar</a>
                                    <?php
                                }
                                ?>
                                    <a href="<?= $v_page_url ?>imprimirPdf/" target="_blank" class="btn btn-default btn-circle" title="Imprimir"><i class="fa fa-print fa-1x"></i> Imprimir</a> 


                                <?php if (count($v_utilizadores) > 0) { ?>

                                    <div class="btn-group pull-right" style=" padding: 10px;">

                                        <button class="btn btn-default" type="button" id="botaoExportar">
                                            <i class="fa fa-file-excel-o"></i>
                                            Exportar(.xls)
                                        </button>

                                    </div><?php } ?>                    

                                <div class="clearfix"></div>
                            </div>

                            <div class="x_content">


                                <div class="table-responsive">
                                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

                                        <thead>
                                            <tr class="headings">
                                              <!-- <th>
                                                <input type="checkbox" id="check-all" class="flat">
                                              </th> -->
                                                <th class="column-title" style="width: auto; text-align: center; vertical-align: middle;">Foto</th>
                                                <th class="column-title">Nome</th>
                                                <th class="column-title">Email </th>
                                                <th class="column-title" style=" text-align: center; ">Função</th>
                                                <th class="column-title" style="text-align: center; ">Estado</th>
                                                <th class="column-title no-link last" style="text-align: center; "><span class="nobr">Opção</span></th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            <!-- <td class="a-center ">
                                              <input type="checkbox" class="flat" name="table_records">
                                            </td> -->
                                            <?php
                                            if (isset($v_utilizadores)) {
                                                if (empty($v_utilizadores)) {
                                                    ?>
                                                <div class="alert alert-danger">
                                                    <strong><span class="fa fa-info"></span></strong> Até o momento não temos utilizador adicionado.
                                                </div>
                                                <?php
                                            }

                                            foreach ($v_utilizadores as $utilizador) {
                                                ?>
                                                <tr class="even pointer">



                                                    <td class="" style="width: auto; text-align: center; vertical-align: middle;">

                                                        <?php
                                                        if ($utilizador->getFoto() == null) {
                                                            $foto = 'm.jpg';
                                                            echo '<img src="' . Geral::DIR_IMG_UTIZADORES . $foto . '" alt="Foto" width="50" height="50" />';
                                                        } else {
                                                            echo '<img src="' . Geral::DIR_IMG_UTIZADORES . $utilizador->getFoto() . '" alt="" width="50" height="50" />';
                                                        }
                                                        ?>

                                                    </td>

                                                    <td class=" " style="width: auto; text-align: left; vertical-align: middle;"> <?= ucfirst($utilizador->getNome()); ?></td>
                                                    <td class=" "style="width: auto; text-align: left; vertical-align: middle;"><?php echo $utilizador->getEmail(); ?></td>
                                                    <td class=" " style="width: auto; text-align: center; vertical-align: middle;"><span style="text-transform:capitalize;"><?= ucfirst(Method::lowerGeneral($utilizador->getFuncao()->getNome())); ?></span></td>
                                                    <td class=" " style="width: auto; text-align: center; vertical-align: middle;">
                                                        <?php
                                                        if ($utilizador->getEstado() == Geral::CONS_UTILIZADOR_ACTIVADO) {
                                                            echo "<b style='color:#0A7521;'>Activado</b>";
                                                        } else {
                                                            echo "<b style='color:#f00;'>Desactivado</b>";
                                                        }
                                                        ?>
                                                    </td>
                                                    <td class="last" style="width: auto; text-align: center; vertical-align: middle;">

                                                        <div class="block-options">
                                                            <a href="<?= $v_page_url ?>ver/<?php echo base64_encode("id") . '/' . base64_encode($utilizador->getId()) ?>" class="btn btn-default btn-circle" title="Ver"><i class="fa fa-eye fa-1x"></i></a> 
                                                            <?php
                                                            /*
                                                            if (Method::lowerGeneral($v_userInfo->getFuncao()->getNome()) != Geral::CONS_PERFIL_FINANCEIRO) {
                                                                ?>
                                                                <a  href="<?= $v_page_url ?>ver/<?php echo base64_encode("id") . '/' . base64_encode($utilizador->getId()) ?>" class="btn btn-warning btn-circle" title="Editar"><i class="fa fa-edit"></i></a>
                                                                <?php
                                                            }
                                                            */
                                                            ?>
                                                            <?php
                                                            /*
                                                            if (Method::lowerGeneral($v_userInfo->getFuncao()->getNome()) == Geral::CONS_PERFIL_ADMINISTRADOR) {
                                                                ?>
                                                                <a href="<?= $v_page_url ?>ver/<?php echo base64_encode("id") . '/' . base64_encode($utilizador->getId()) ?>" class="btn btn-danger  btn-circle" title="Eliminar"><i class="fa fa-remove"></i></a>
                                                                    <?php
                                                                }
                                                            */
                                                                ?> 
                                                        </div>

                                                    </td>
                                                </tr>
                                                <?php
                                            }
                                        }
                                        ?>

                                        </tbody>
                                    </table>
                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /page content -->



        <?php
// Modal de registar utilizador 
        include_once 'app/views/utilizador/modal/modal_registar.phtml';
// Fim Modal de registar utilizador 
        ?>



        <?php
        include_once 'app/views/public/footer.phtml';
        include_once 'app/views/public/javascript.phtml';
        ?>
        <script src="/Muxima_Helpdesk/web-files/default/js/validacao/parsley.js"></script>
        <script src="/Muxima_Helpdesk/web-files/default/js/validacao/pt-pt.js"></script>

        <?php
        include_once 'app/views/public/end.phtml';
        ?>

