<!DOCTYPE HTML>
<html>
	<head>
		<?php
        echo' <title>' . $v_title_page . '</title>';
        include_once 'app/views/public/adm_cabecalho.phtml';
        ?>
		<body>
			<div id="wrapper">
				<!----->
				<nav class="navbar-default navbar-static-top" role="navigation">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<h1>
							<a class="navbar-brand" href="#">EDITOR <span class="fa fa-edit"></span></a>
						</h1>
                    </div>
                    <?php include_once 'app/views/public/pesquisar.phtml'; ?>
					
					<!-- Brand and toggle get grouped for better mobile display -->
					<!-- Menu TOPO -->
					<?php include_once 'app/views/public/menu_topo.phtml'; ?>
					<!-- /.Menu TOPO -->
					<div class="clearfix"></div>
					<div class="navbar-default sidebar" role="navigation">
                        <!-- Menu PRINCIPAL -->
                        <?php include_once 'app/views/public/menu/menu.phtml'; ?>
                        <!-- / Menu PRINCIPAL -->
					</div>
				</nav>
							<div id="page-wrapper" class="gray-bg dashbard-1">
								<div class="content-main">
									<!--banner-->
									<div class="banner">
										<h2>
										</h2>
									</div>
									<!--//banner-->
									<!--faq-->
									<div class="blank">
										<div class="blank-page">


                                        <div class="table-responsive">
        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

            <thead>
                <tr class="headings">
                  <!-- <th>
                    <input type="checkbox" id="check-all" class="flat">
                  </th> -->
                    <th class="column-title" style="width: auto; text-align: center; vertical-align: middle;">#</th>
                    <th class="column-title" style=" text-align: center; ">Nome</th>
                    <th class="column-title" style=" text-align: center; ">Estado</th>
                    <th class="column-title" style="text-align: center; ">Utilizador</th>
                    <th class="column-title no-link last" style="text-align: center; "><span class="nobr">Opção</span></th>
                </tr>
            </thead>

            <tbody>
                <!-- <td class="a-center ">
                  <input type="checkbox" class="flat" name="table_records">
                </td> -->
                <?php
                if (isset($v_publicacoes)) {

                    if (empty($v_publicacoes)) {
                        ?>
                    <div class="alert alert-danger">
                        <strong><span class="fa fa-info"></span></strong> Não encontramos resultado da pesquisa.
                    </div>
<?php
}
$cont = 0;
foreach ($v_publicacoes as $v_publicacao) {
?>
                    <tr class="even pointer">



                        <td class="" style="width: auto; text-align: center; vertical-align: middle;">

<?php
echo ( ++$cont);
?>

                        </td>

                        <td class=" " style="width: auto; text-align: left; vertical-align: middle;"><?= $v_publicacao->getTitulo()?> </td>
                        <td class=" "style="width: auto; text-align: left; vertical-align: middle;">
                        <?php if($v_publicacao->getEstado()==0)
                        {
                            echo "<b style='color:#f00;'>Não Publicado</b>";
                        }
                        elseif($v_publicacao->getEstado()==1)
                        {
                            echo "<b style='color:#2532EB;'>Publicado</b>";
                        }?></td>
                        <td class=" "style="width: auto; text-align: left; vertical-align: middle;"><?= $v_publicacao->getUtilizador()->getNome()?></td>
                        <td class="last" style="width: auto; text-align: center; vertical-align: middle;">

                            <div class="block-options">
                                <a href="<?= $v_page_url ?>ver/<?php echo base64_encode("id") . '/' . base64_encode($v_publicacao->getId())?>" class="btn btn-default btn-circle" title="Ver"><i class="fa fa-eye fa-1x"></i></a> 
                                
                                <?php
                                    if(Method::lowerGeneral($v_userInfo->getFuncao()->getNome()) == Geral::CONS_PERFIL_ADMINISTRADOR)
                                    {
                                    ?>
                                    <a  href="<?= $v_page_url ?>editar/<?php echo base64_encode("id") . '/' . base64_encode($v_publicacao->getId()) ?>" class="btn btn-warning btn-circle" title="Editar"><i class="fa fa-edit"></i></a>
                                    <?php
                                    }
                                ?>
                            </div>

                        </td>
                    </tr>
<?php
}
}
?>

            </tbody>
        </table>
    </div>
                                            
                                        





										</div>
									</div>
									<!--//faq-->
									<!---->
                                    <!-- footer -->
                                    <?php include_once 'app/views/public/adm_footer.phtml'; ?>
                                    <!-- /footer -->
								</div>
							</div>
            <div class="clearfix"></div>
            </div>
            <!---->
			<!--scrolling js-->
			<?php include_once 'app/views/public/adm_javascript.phtml'; ?>
            <!--//scrolling js-->
        </body>
</html>

