<!DOCTYPE html>
<html lang="pt">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title><?= $v_title_page; ?></title>

    <?php
    include_once 'app/views/public/adm/head.phtml';
    ?>
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <?php
        include_once 'app/views/public/adm/topNavigation.phtml';
        ?>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar elevation-4 sidebar-light-warning">
            <!-- Brand Logo -->
            <?php
            include_once 'app/views/public/adm/logo.phtml';
            ?>
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <?php
                include_once 'app/views/public/adm/userInfo.phtml';
                ?>
                <!-- Sidebar Menu -->
                <?php
                include_once 'app/views/public/menuLateral.phtml';
                ?>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"><?= $v_page_context; ?></h1>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <!-- Main row -->
                    <div class="row">
                        <!-- / Corpo da página INÍCIO -->

                        <div class="col-6">
                            <div class="card">

                                <form role="form" id="formProduto" method="POST" action="<?= $v_page_url; ?>actualizar">
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label for="titulo-evento">Título</label>
                                            <input type="hidden" value="<?= $v_entity->getID(); ?>" name="id_blog">
                                            <input type="text" name="titulo" class="form-control" id="nome-evento" placeholder="Nome da <?= $v_page_context; ?>" value="<?= $v_entity->getTitulo(); ?>">
                                        </div>
                                        <div class="form-group">
                                            <label for="texto-evento">Texto</label>
                                            <textarea name="texto" rows="8" class="form-control" id="texto-evento" placeholder="Descrição do <?= $v_page_context; ?>"><?= rtrim(ltrim($v_entity->getTexto())); ?></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label for="estado-<?= $v_page_context; ?>">Estado</label>
                                            <select id="estado-<?= $v_page_context; ?>" name="estado" class="form-control" required>
                                                <?php
                                                if ($v_entity->getEstado() == Geral::CONS_N_PUBLICADO) {
                                                    echo "<option value='0' selected>Não Publlicado</option>";
                                                    echo "<option value='1'>Publlicado</option>";
                                                } else if ($v_entity->getEstado() == Geral::CONS_PUBLICADO) {
                                                    echo "<option value='0'>Não Publlicado</option>";
                                                    echo "<option value='1' selected>Publlicado</option>";
                                                } ?>
                                            </select>
                                        </div>
                                    </div>
                                    <!-- /.card-body -->
                                    <!--<div class="card-footer">
                  <button type="submit" class="btn btn-primary">Gravar <?= $v_page_context; ?></button>
                </div>-->
                                    <div class="ln_solid"></div>
                                    <div class="form-group">
                                        <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                                            <a style="cursor:pointer" onclick="voltar();" class="btn btn-default btn-circle" title="Voltar"><i class="fa fa-chevron-left"></i><strong> Voltar</strong></a>
                                            <button type="submit" class="btn btn-primary">Actualizar <?= $v_page_context; ?></button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <div class="col-6">
                            <div class="card">
                                <div class="card-body">
                                    <span style="font-size:12px;">Gravado em: <?= $v_entity->getData(); ?> &bull; Por: <b><?= $v_entity->getUtilizador()->getNome(); ?></b></span>
                                    <hr>
                                    <div class="text-center">
                                        <?php
                                        if (isset($v_entity)) {
                                            $foto = $v_entity->getFoto();
                                            if (!$v_entity->getFoto() == null) {
                                                echo '<img style="width:100%;" src="' . Geral::DIR_IMG_BLOG . $foto . '" alt="Imagem de ' . $v_entity->getTitulo() . '" title="Imagem de ' . $v_entity->getTitulo() . '" />';
                                            } else {
                                                echo "<span style='color:#f00;'> * Artigo sem imagem * </span>";
                                            }
                                        }
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- / Corpo da página FIM -->
                    </div>
                    <!-- /.row -->
                </div>
                <!--/. container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
        <?php
        //Inclusão da Modal de upload de ficheiros multimédia na ficha do imóvel 
        include_once 'modal/modal-uploadMultimedia.php';
        // Fim da Modal de upload de ficheiros multimédia na ficha do imóvel 
        ?>
        <!-- Main Footer -->
        <?php
        include_once 'app/views/public/adm/foot.phtml';
        ?>

    </div>
    <!-- ./wrapper -->

    <?php
    include_once 'app/views/public/adm/javascript.phtml';
    include_once 'app/views/public/adm/datatables.phtml';
    ?>
</body>

</html>