<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title><?= $v_title_page;?></title>

  <?php
    include_once 'app/views/public/adm/head.phtml';
    include_once 'app/views/public/adm/selectorCSS.phtml';
  ?>
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
  <div class="wrapper">
    <!-- Navbar -->
    <?php
      include_once 'app/views/public/adm/topNavigation.phtml';
    ?>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar elevation-4 sidebar-light-warning">
      <!-- Brand Logo -->
      <?php
        include_once 'app/views/public/adm/logo.phtml';
      ?>
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <?php
        include_once 'app/views/public/adm/userInfo.phtml';
        ?>
        <!-- Sidebar Menu -->
        <?php
        include_once 'app/views/public/menuLateral.phtml';
        ?>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark"><?= $v_page_context;?></h1>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- Main row -->
          <div class="row">
            <!-- / Corpo da página INÍCIO -->
            <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title"></h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" id="formProduto" method="POST" action="<?= $v_page_url;?>registar">
                <div class="card-body">
                  <div class="form-group">
                    <label for="nome-estudante">Nome</label>
                    <input type="text" name="nome" class="form-control" id="nome-estudante" placeholder="Nome do <?= $v_page_context;?>">
                  </div>
                  <div class="form-group">
                    <label for="email-estudante">Email</label>
                    <input type="email" name="email" class="form-control" id="email-estudante" placeholder="Email do <?= $v_page_context;?>">
                  </div>
                  <div class="form-group">
                    <label for="telefone-estudante">Telefone</label>
                    <input type="text" name="telefone" class="form-control" id="telefone-estudante" placeholder="Telefone do <?= $v_page_context;?>">
                  </div>
                  <div class="form-group">
                    <label for="escola">Escola</label>
                    <select class="form-control select2" name="escola" id="escola">
                      <option value="">-- Escolha a escola --</option> 
                    <?php
                      if (isset($v_escolas)) {
                        if (empty($v_escolas)) {
                          echo "Sem tipo";
                        }
                        foreach ($v_escolas as $escola){
                          ?>
                          <option value="<?= $escola->getId();?>"><?= $escola->getNome();?></option>
                          <?php
                        }
                      }
                        ?>
                  </select>
                  </div>
                  <div class="form-group">
                    <label for="passe-estudante">Palavra-passe</label>
                    <input type="password" name="passe" class="form-control" id="passe-estudante" placeholder="Palavra-passe do <?= $v_page_context;?>">
                  </div>
                  <div class="form-group">
                    <label for="perfil">Perfil</label>
                    <select class="form-control select2" name="perfil" id="perfil" required>
                      <option value="">-- Escolha o perfil --</option> 
                    <?php
                      if (isset($v_perfis)) {
                        if (empty($v_perfis)) {
                          echo "Sem perfil";
                        }
                        foreach ($v_perfis as $perfil){
                          ?>
                          <option value="<?= $perfil->getId();?>"><?= $perfil->getNome();?></option>
                          <?php
                        }
                      }
                        ?>
                  </select>
                  </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <a style="cursor:pointer" onclick="voltar();" class="btn btn-default btn-circle" title="Voltar"><i class="fa fa-chevron-left"></i><strong> Voltar</strong></a>
                    <button type="submit" class="btn btn-primary">Gravar <?= $v_page_context;?></button>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
            
            <!-- / Corpo da página FIM -->
          </div>
          <!-- /.row -->
        </div>
        <!--/. container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <?php
    include_once 'app/views/public/adm/foot.phtml';
    ?>
    
  </div>
  <!-- ./wrapper -->

  <?php
    include_once 'app/views/public/adm/javascript.phtml';
    include_once 'app/views/public/adm/datatables.phtml';
    include_once 'app/views/public/adm/selectorJS.phtml';
  ?>
  <script type="text/javascript">
$(document).ready(function () {
  $.validator.setDefaults({
  });
  $('#formProduto').validate({
    rules: {
      codigo: {
        required: true
      },
      nome: {
        required: true
      },
      preco: {
        required: true
      },
      origem: {
        required: true
      },
      marca: {
        required: true
      },
      categoria: {
        required: true
      },
      estado: {
        required: true
      },
      descricao: {
        required: true,
        minlength: 10
      },
      terms: {
        required: true
      },
    },
    messages: {
      codigo: {
        required: "Por favor, insira o código do estudante"
      },
      nome: {
        required: "Por favor, insira o nome do estudante"
      },
      preco: {
        required: "Por favor, insira o preço do estudante"
      },
      origem: {
        required: "Por favor, insira a origem do estudante"
      },
      marca: {
        required: "Por favor, insira a marca do estudante"
      },
      categoria: {
        required: "Por favor, insira a categoria do estudante"
      },
      estado: {
        required: "É importante informar o estado do estudante"
      },
      descricao: {
        required: "É necessário que descreva o estudante para melhor detalhes",
        minlength: "Descrição é muito curta. Deve ter mais de 10 caracteres."
      }
      /*,
      terms: "Please accept our terms"*/
    },
    errorElement: 'span',
    errorPlacement: function (error, element) {
      error.addClass('invalid-feedback');
      element.closest('.form-group').append(error);
    },
    highlight: function (element, errorClass, validClass) {
      $(element).addClass('is-invalid');
    },
    unhighlight: function (element, errorClass, validClass) {
      $(element).removeClass('is-invalid');
    }
  });
});
</script>
</body>
</html>