<!-- SEO -->
<!-- This site is optimized with the Yoast SEO plugin v6.3.1 - https://yoast.com/wordpress/plugins/seo/ -->
<meta name="description" content="O Torneio Intercolegial Tina Tune é um conjunto de festivais de carácter social com a finalidade de colaborar com a formação pedagógica, filosófica e artística dos estudantes, por meio das várias formas de manifestação da arte." />
<meta property="og:locale" content="pt_PT" />
<meta property="og:type" content="website" />
<meta property="og:title" content="Oficial | Torneio Intercolegial Tina Tune" />
<meta property="og:description" content="O Torneio Intercolegial Tina Tune é um conjunto de festivais de carácter social com a finalidade de colaborar com a formação pedagógica, filosófica e artística dos estudantes, por meio das várias formas de manifestação da arte." />
<meta property="og:url" content="https://www.intercolegialtinatune.co.ao/web-files/images/logo_front.png" />
<meta property="og:site_name" content="Oficial | Torneio Intercolegial Tina Tune" />
<meta property="og:image" content="https://www.intercolegialtinatune.co.ao/web-files/images/logo_front.png" />
<meta property="og:image:secure_url" content="https://www.intercolegialtinatune.co.ao/web-files/images/logo_front.png" />
<meta name="google:card" content="summary_large_image" />
<meta name="google:description" content="O Torneio Intercolegial Tina Tune é um conjunto de festivais de carácter social com a finalidade de colaborar com a formação pedagógica, filosófica e artística dos estudantes, por meio das várias formas de manifestação da arte." />
<meta name="google:title" content="Oficial | Torneio Intercolegial Tina Tune" />
<meta name="google:image" content="https://www.intercolegialtinatune.co.ao/web-files/images/logo_front.png" />
<!-- // SEO-->
<!--===============================================================================================-->
<!-- Font Awesome Icons -->
<link rel="stylesheet" href="https://www.intercolegialtinatune.co.ao/web-files/adm/plugins/fontawesome-free/css/all.min.css">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="https://www.intercolegialtinatune.co.ao/web-files/adm/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="https://www.intercolegialtinatune.co.ao/web-files/adm/dist/css/adminlte.min.css">
<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">


<link rel="stylesheet" href="https://www.intercolegialtinatune.co.ao/web-files/css/multimedia.css">

<!-- ========== Favicon Ico ========== -->
<link rel="icon" href="https://www.intercolegialtinatune.co.ao/web-files/images/icon.png" type="image/ico" />