<header class="header navbar fixed-top navbar-expand-md">
    <div class="container">
        <a class="navbar-brand logo" href="<?= $v_page_url;?>">
            <img src="/jam/web-files/assets/img/logo.png" alt="JAM"/>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#headernav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="lnr lnr-text-align-right"></span>
        </button>
        <div class="collapse navbar-collapse flex-sm-row-reverse" id="headernav">
            <ul class=" nav navbar-nav menu">
                <li class="nav-item">
                    <a class="nav-link active" href="<?= $v_page_url;?>"><b>Início</b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="<?= $v_page_url;?>intercolegial"><b>Intercolegial</b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="<?= $v_page_url;?>am"><b>AM</b></a>
                </li>
                <!--
                <li class="nav-item">
                    <a class="nav-link " href="#"><b>Torneio</b></a>
                </li>
                -->
                <li class="nav-item">
                    <a class="nav-link " href="<?= $v_page_url;?>contactos"><b>Contactos</b></a>
                </li>
                <li class="search_btn">
                    <a  href="#">
                       <i class="ion-ios-search"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</header>