<!-- REQUIRED SCRIPTS -->
<!-- jQuery -->
<script src="/intercolegial/web-files/adm/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="/intercolegial/web-files/adm/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- overlayScrollbars -->
<script src="/intercolegial/web-files/adm/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="/intercolegial/web-files/adm/dist/js/adminlte.js"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="/intercolegial/web-files/adm/dist/js/demo.js"></script>

<!-- PAGE PLUGINS -->
<!-- jQuery Mapael -->
<script src="/intercolegial/web-files/adm/plugins/jquery-mousewheel/jquery.mousewheel.js"></script>
<script src="/intercolegial/web-files/adm/plugins/raphael/raphael.min.js"></script>
<script src="/intercolegial/web-files/adm/plugins/jquery-mapael/jquery.mapael.min.js"></script>
<script src="/intercolegial/web-files/adm/plugins/jquery-mapael/maps/usa_states.min.js"></script>
<!-- ChartJS -->
<script src="/intercolegial/web-files/adm/plugins/chart.js/Chart.min.js"></script>

<!-- PAGE SCRIPTS -->
<script src="/intercolegial/web-files/adm/dist/js/pages/dashboard2.js"></script>
<script src="/intercolegial/web-files/adm/plugins/jquery-validation/jquery.validate.min.js"></script>

<script>
    function voltar()
    {
        window.history.back();
    }
</script>