<script src="https://www.intercolegialtinatune.co.ao/web-files/adm/plugins/select2/js/select2.full.min.js"></script>
<script src="https://www.intercolegialtinatune.co.ao/web-files/adm/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js"></script>
<script src="https://www.intercolegialtinatune.co.ao/web-files/adm/plugins/moment/moment.min.js"></script>
<script src="https://www.intercolegialtinatune.co.ao/web-files/adm/plugins/inputmask/min/jquery.inputmask.bundle.min.js"></script>
<script>
  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2()

    //Initialize Select2 Elements
    $('.select2bs4').select2({
      theme: 'bootstrap4'
    })
  })
</script>