<div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
				
                    <li>
                        <a href="/autenticador/Inicial/index" class=" hvr-bounce-to-right"><i class="fa fa-dashboard nav_icon "></i><span class="nav-label">Painel Inicial</span> </a>
                    </li>
                    <!--
                    <li>
                        <a href="gallery.html" class=" hvr-bounce-to-right"><i class="fa fa-picture-o nav_icon"></i> <span class="nav-label">Galeria</span> </a>
                    </li>
                    -->
                    <li>
                        <a href="#" class=" hvr-bounce-to-right"><i class="fa fa-list nav_icon"></i> <span class="nav-label">Publicações</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="/autenticador/publicacao/" class=" hvr-bounce-to-right"><i class="fa fa-align-left nav_icon"></i>Gerir</a></li>
                        </ul>
                    </li>
                   
                    <!--
                    <li>
                        <a href="#" class=" hvr-bounce-to-right"><i class="fa fa-cog nav_icon"></i> <span class="nav-label">Settings</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="signin.html" class=" hvr-bounce-to-right"><i class="fa fa-sign-in nav_icon"></i>Signin</a></li>
                            <li><a href="signup.html" class=" hvr-bounce-to-right"><i class="fa fa-sign-in nav_icon"></i>Singup</a></li>
                        </ul>
                    </li>
                    -->
                    <li>
                        <a href="#" class=" hvr-bounce-to-right"><i class="fa fa-users nav_icon"></i> <span class="nav-label">Utilizadores</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="/autenticador/Utilizador/" class=" hvr-bounce-to-right"><i class="fa fa-users nav_icon"></i>Gerir</a></li>
                        </ul>
                    </li>
                </ul>
            </div>