<section id="home-section" class="hero js-fullheight">
    <h3 class="vr">Intercolegial <span>Tina Tune</span></h3>
    <!--<div id="timer" class="text-center">
        <div class="time" id="days"></div>
        <div class="time" id="hours"></div>
        <div class="time" id="minutes"></div>
        <div class="time" id="seconds"></div>
    </div>-->
    <div class="home-slider owl-carousel js-fullheight">
        <div class="slider-item js-fullheight">
            <div class="overlay"></div>
            <div class="container-fluid px-0">
                <div class="row d-md-flex no-gutters slider-text js-fullheight align-items-end justify-content-end" data-scrollax-parent="true">
                    <div class="one-third order-md-last js-fullheight img" style="background-image:url(https://www.intercolegialtinatune.co.ao/web-files/images/bg.jpg);">
                        <div class="overlay"></div>
                    </div>
                    <div class="one-forth js-fullheight d-flex align-items-start align-items-md-center ftco-animate" data-scrollax=" properties: { translateY: '70%' }">
                        <div class="text mt-4 mt-md-0">
                            <h1 class="mb-4">Torneio Intercolegial <span>Tina Tune</span></span></h1>
                            <h2 class="mb-4">Agarra o teu sonho</h2>
                            <p><a href="#" data-toggle="modal" data-target="#inscricaoModal" class="btn btn-primary py-3 px-4">Inscrever-se</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="slider-item js-fullheight">
            <div class="overlay"></div>
            <div class="container-fluid px-0">
                <div class="row d-flex no-gutters slider-text js-fullheight align-items-end justify-content-end" data-scrollax-parent="true">
                    <div class="one-third order-md-last js-fullheight img" style="background-image:url(https://www.intercolegialtinatune.co.ao/web-files/images/bg_2.jpg);">
                        <div class="overlay"></div>
                    </div>
                    <div class="one-forth js-fullheight d-flex align-items-start align-items-md-center ftco-animate" data-scrollax=" properties: { translateY: '70%' }">
                        <div class="text mt-4 mt-md-0">
                            <h1 class="mb-4">Agarra o teu sonho<span></span> </h1>
                            <h1 class="mb-4">Torneio Intercolegial<span></span> </h1>
                            <h2 class="mb-4"></h2>
                            <p><a href="#about-section" class="btn btn-primary py-3 px-4">Saiba mais</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>