<section class="ftco-section bg-light" id="schedule-section">
    <div class="container">
        <div class="row justify-content-center pb-5">
            <div class="col-md-12 heading-section text-center ftco-animate">
                <span class="subheading">Nosso</span>
                <h2 class="mb-4">Calendário de Eventos</h2>
                <p></p>
            </div>
        </div>
        <div class="ftco-schedule">
            <div class="row">
                <div class="col-md-4 nav-link-wrap">
                    <div class="nav flex-column nav-pills" id="c-eventos-tab" role="tablist" aria-orientation="vertical">
                        <a class="nav-link ftco-animate active" id="c-eventos-1-tab" data-toggle="pill" href="#c-eventos-1" role="tab" aria-controls="c-eventos-1" aria-selected="true">28 de Nov 2020<span></span></a>
                        <a class="nav-link ftco-animate" id="c-eventos-2-tab" data-toggle="pill" href="#c-eventos-2" role="tab" aria-controls="c-eventos-2" aria-selected="false">29 de Nov 2020<span></span></span></a>
                        <!--
                        <a class="nav-link ftco-animate" id="c-eventos-3-tab" data-toggle="pill" href="#c-eventos-3" role="tab" aria-controls="c-eventos-3" aria-selected="false">Dia 03 <span>23 <?= date('M Y') ?></span></a>
                        <a class="nav-link ftco-animate" id="c-eventos-4-tab" data-toggle="pill" href="#c-eventos-4" role="tab" aria-controls="c-eventos-4" aria-selected="false">Dia 04 <span>24 <?= date('M Y') ?></span></a>
                        -->
                    </div>
                </div>
                <div class="col-md-8 tab-wrap">

                    <div class="tab-content" id="c-eventos-tabContent">

                        <div class="tab-pane fade show active" id="c-eventos-1" role="tabpanel" aria-labelledby="day-1-tab">
                            <div class="speaker-wrap ftco-animate d-flex">
                                <div class="img speaker-img" style="background-image: url(https://intercolegialtinatune.co.ao/web-files/uploads/eventos/ruca-fest.jpeg);"></div>
                                <div class="text pl-md-5">
                                    <!--<span class="time">10:00 ás 14:00</span>-->
                                    <h2><a href="#">Festival Drive In (Ruca Fest Intercolégial By T’Leva)</a></h2>
                                    <p style="color: #000000;">O festival será realizado no parque de estacionamento do Talatona Shopping nos dias 28 e 29 de novembro em duas sessões por dia.</p>

                                </div>
                            </div>
                            <div class="speaker-wrap ftco-animate d-flex">
                                <div class="img speaker-img" style="background-image: url(https://intercolegialtinatune.co.ao/web-files/uploads/eventos/ruca-fest.jpeg);"></div>
                                <div class="text pl-md-5">
                                    <!--<span class="time">10:00 ás 14:00</span>-->
                                    <h2><a href="#">Festival Drive In (Ruca Fest Intercolégial By T’Leva)</a></h2>
                                    <p style="color: #000000;">O festival será realizado no parque de estacionamento do Talatona Shopping nos dias 28 e 29 de novembro em duas sessões por dia.</p>

                                </div>
                            </div>
                        </div>

                        <div class="tab-pane fade" id="c-eventos-2" role="tabpanel" aria-labelledby="c-eventos-day-2-tab">
                            <div class="speaker-wrap ftco-animate d-flex">
                                <div class="img speaker-img" style="background-image: url(https://intercolegialtinatune.co.ao/web-files/uploads/eventos/ruca-fest.jpeg);"></div>
                                <div class="text pl-md-5">
                                    <!--<span class="time">10:00 ás 14:00</span>-->
                                    <h2><a href="#">Festival Drive In (Ruca Fest Intercolégial By T’Leva)</a></h2>
                                    <p style="color: #000000;">O festival será realizado no parque de estacionamento do Talatona Shopping nos dias 28 e 29 de novembro em duas sessões por dia.</p>

                                </div>
                            </div>
                            <div class="speaker-wrap ftco-animate d-flex">
                                <div class="img speaker-img" style="background-image: url(https://intercolegialtinatune.co.ao/web-files/uploads/eventos/ruca-fest.jpeg);"></div>
                                <div class="text pl-md-5">
                                    <!--<span class="time">10:00 ás 14:00</span>-->
                                    <h2><a href="#">Festival Drive In (Ruca Fest Intercolégial By T’Leva)</a></h2>
                                    <p style="color: #000000;">O festival será realizado no parque de estacionamento do Talatona Shopping nos dias 28 e 29 de novembro em duas sessões por dia.</p>

                                </div>
                            </div>
                        </div>
                        <!--
                        <div class="tab-pane fade" id="c-eventos-3" role="tabpanel" aria-labelledby="c-eventos-day-3-tab">
                            <div class="speaker-wrap ftco-animate d-flex">
                                <div class="img speaker-img" style="background-image: url(https://www.intercolegialtinatune.co.ao/web-files/images/person_1.png);"></div>
                                <div class="text pl-md-5">
                                    <span class="time">08:00AM - 10:00AM</span>
                                    <h2><a href="#">Titulo</a></h2>
                                    <p style="color: #000000;">O Torneio Intercolegial Tina Tune é um conjunto de festivais de caráter
social com a finalidade de colaborar com a formação pedagógica, filosófica e
artística dos estudantes, por meio das várias formas de manifestação da arte</p>
                                    
                                </div>
                            </div>
                            <div class="speaker-wrap ftco-animate d-flex">
                                <div class="img speaker-img" style="background-image: url(https://www.intercolegialtinatune.co.ao/web-files/images/person_1.png);"></div>
                                <div class="text pl-md-5">
                                    <span class="time">08:00AM - 10:00AM</span>
                                    <h2><a href="#">Titulo</a></h2>
                                    <p style="color: #000000;">O Torneio Intercolegial Tina Tune é um conjunto de festivais de caráter
social com a finalidade de colaborar com a formação pedagógica, filosófica e
artística dos estudantes, por meio das várias formas de manifestação da arte</p>
                                    
                                </div>
                            </div>
                            <div class="speaker-wrap ftco-animate d-flex">
                                <div class="img speaker-img" style="background-image: url(https://www.intercolegialtinatune.co.ao/web-files/images/person_1.png);"></div>
                                <div class="text pl-md-5">
                                    <span class="time">08:00AM - 10:00AM</span>
                                    <h2><a href="#">Titulo</a></h2>
                                    <p style="color: #000000;">O Torneio Intercolegial Tina Tune é um conjunto de festivais de caráter
social com a finalidade de colaborar com a formação pedagógica, filosófica e
artística dos estudantes, por meio das várias formas de manifestação da arte</p>
                                    
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="c-eventos-4" role="tabpanel" aria-labelledby="c-eventos-day-4-tab">
                            <div class="speaker-wrap ftco-animate d-flex">
                                <div class="img speaker-img" style="background-image: url(https://www.intercolegialtinatune.co.ao/web-files/images/person_1.png);"></div>
                                <div class="text pl-md-5">
                                    <span class="time">08:00AM - 10:00AM</span>
                                    <h2><a href="#">Titulo</a></h2>
                                    <p style="color: #000000;">O Torneio Intercolegial Tina Tune é um conjunto de festivais de caráter
social com a finalidade de colaborar com a formação pedagógica, filosófica e
artística dos estudantes, por meio das várias formas de manifestação da arte</p>
                                    
                                </div>
                            </div>
                            <div class="speaker-wrap ftco-animate d-flex">
                                <div class="img speaker-img" style="background-image: url(https://www.intercolegialtinatune.co.ao/web-files/images/person_1.png);"></div>
                                <div class="text pl-md-5">
                                    <span class="time">08:00AM - 10:00AM</span>
                                    <h2><a href="#">Titulo</a></h2>
                                    <p style="color: #000000;">O Torneio Intercolegial Tina Tune é um conjunto de festivais de caráter
social com a finalidade de colaborar com a formação pedagógica, filosófica e
artística dos estudantes, por meio das várias formas de manifestação da arte</p>
                                    
                                </div>
                            </div>
                            <div class="speaker-wrap ftco-animate d-flex">
                                <div class="img speaker-img" style="background-image: url(https://www.intercolegialtinatune.co.ao/web-files/images/person_1.png);"></div>
                                <div class="text pl-md-5">
                                    <span class="time">08:00AM - 10:00AM</span>
                                    <h2><a href="#">Titulo</a></h2>
                                    <p style="color: #000000;">O Torneio Intercolegial Tina Tune é um conjunto de festivais de caráter
social com a finalidade de colaborar com a formação pedagógica, filosófica e
artística dos estudantes, por meio das várias formas de manifestação da arte</p>
                                    
                                </div>
                            </div>
                        </div>
                        -->

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>