<footer class="ftco-footer ftco-section">
		<div class="container">
			<div class="row mb-5">
				<div class="col-md">
					<div class="ftco-footer-widget mb-4">
						<!--<h2 class="ftco-heading-2">Realização</h2>-->
						<div class="">
							<img src="https://www.jam.co.ao/web-files/assets/img/logo.png" alt="JAM">
						</div>
						<p></p>
						<ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
							<li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
							<li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
							<li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
						</ul>
					</div>
				</div>
				<div class="col-md">
					<div class="ftco-footer-widget mb-4 ml-md-4">
						<h2 class="ftco-heading-2">Mapa</h2>
						<ul class="list-unstyled">
							<li><a href="#home-section"><span class="icon-long-arrow-right mr-2"></span>Início</a></li>
							<li><a href="#about-section"><span class="icon-long-arrow-right mr-2"></span>Torneio intercolegial</a></li>
							<li><a href="#schedule-section"><span class="icon-long-arrow-right mr-2"></span>Calendário</a></li>
							<li><a href="#blog-section"><span class="icon-long-arrow-right mr-2"></span>Novidades</a></li>
							<li><a href="#contact-section"><span class="icon-long-arrow-right mr-2"></span>Contactos</a></li>
						</ul>
					</div>
				</div>
				<div class="col-md">
					<div class="ftco-footer-widget mb-4">
						<h2 class="ftco-heading-2">Conta</h2>
						<ul class="list-unstyled">
							<li><a href="https://www.intercolegialtinatune.co.ao/Login/" target="blank"><span class="icon-long-arrow-right mr-2"></span>Entrar</a></li>
							<li><a href="#inscricao" data-toggle="modal" data-target="#inscricaoModal"><span class="icon-long-arrow-right mr-2"></span>Inscrever-se</a></li>
						</ul>
					</div>
				</div>
				<div class="col-md">
					<div class="ftco-footer-widget mb-4">
						<h2 class="ftco-heading-2">Alguma dúvida?</h2>
						<div class="block-23 mb-3">
							<ul>
								<li><span class="icon icon-map-marker"></span><span class="text">Estrada do Patriota, Edif. Kissange, 1º Andar A</span></li>
								<li><a href="#"><span class="icon icon-phone"></span><span class="text">+244 931 199 396</span></a></li>
								<li><a href="#"><span class="icon icon-envelope"></span><span class="text">intercolegialtinatune@jam.co.ao</span></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 text-center">

					<p>
						<?php echo date('Y'); ?> &copy; JAM ENT &bull; <a href="https://mrvipaji.ao/" target="new">MRVIPAJI - Quizá, el mejor del mundo</a>
					</p>
				</div>
			</div>
		</div>
	</footer>