<head>
	<title><?= $v_title_page; ?></title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- This site is optimized with the Yoast SEO plugin v6.3.1 - https://yoast.com/wordpress/plugins/seo/ -->
	<meta name="description" content="O Torneio Intercolegial Tina Tune é um conjunto de festivais de carácter social com a finalidade de colaborar com a formação pedagógica, filosófica e artística dos estudantes, por meio das várias formas de manifestação da arte." />
	<meta property="og:locale" content="pt_PT" />
	<meta property="og:type" content="website" />
	<meta property="og:title" content="Oficial | Torneio Intercolegial Tina Tune" />
	<meta property="og:description" content="O Torneio Intercolegial Tina Tune é um conjunto de festivais de carácter social com a finalidade de colaborar com a formação pedagógica, filosófica e artística dos estudantes, por meio das várias formas de manifestação da arte." />
	<meta property="og:url" content="https://www.intercolegialtinatune.co.ao/web-files/images/logo_front.png" />
	<meta property="og:site_name" content="Oficial | Torneio Intercolegial Tina Tune" />
	<meta property="og:image" content="https://www.intercolegialtinatune.co.ao/web-files/images/logo_front.png" />
	<meta property="og:image:secure_url" content="https://www.intercolegialtinatune.co.ao/web-files/images/logo_front.png" />
	<meta name="google:card" content="summary_large_image" />
	<meta name="google:description" content="O Torneio Intercolegial Tina Tune é um conjunto de festivais de carácter social com a finalidade de colaborar com a formação pedagógica, filosófica e artística dos estudantes, por meio das várias formas de manifestação da arte." />
	<meta name="google:title" content="Oficial | Torneio Intercolegial Tina Tune" />
	<meta name="google:image" content="https://www.intercolegialtinatune.co.ao/web-files/images/logo_front.png" />
	<!-- // SEO-->

	<link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">

	<link rel="stylesheet" href="/intercolegial/web-files/css/open-iconic-bootstrap.min.css">
	<link rel="stylesheet" href="/intercolegial/web-files/css/animate.css">

	<link rel="stylesheet" href="/intercolegial/web-files/css/owl.carousel.min.css">
	<link rel="stylesheet" href="/intercolegial/web-files/css/owl.theme.default.min.css">
	<link rel="stylesheet" href="/intercolegial/web-files/css/magnific-popup.css">

	<link rel="stylesheet" href="/intercolegial/web-files/css/aos.css">

	<link rel="stylesheet" href="/intercolegial/web-files/css/ionicons.min.css">

	<link rel="stylesheet" href="/intercolegial/web-files/css/flaticon.css">
	<link rel="stylesheet" href="/intercolegial/web-files/css/icomoon.css">
	<link rel="stylesheet" href="/intercolegial/web-files/css/style.css">
	<link rel="icon" href="/intercolegial/web-files/images/icon.png" type="image/ico" />
</head>