<section class="ftco-section ftco-speakers" id="speakers-section">
    <div class="container">
        <div class="row justify-content-center pb-5">
            <div class="col-md-12 heading-section heading-section-white text-center ftco-animate">
                <span class="subheading">Nossas</span>
                <h2 class="mb-4">Modalidades</h2>
                <p></p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm modalidades">
                <h3>Música</h3>
                <p>
                    Este concurso visa incentivar o jovem artista a participar dos eventos intercolegiais, permitindo a exteriorização, perante o público, de suas potencialidades, em termos de arte musical nativa; buscar a preservação de nossos valores de origem, temas, rítmos, usos e costumes, manifestando-os no presente e projetando-o através dos tempos.
                </p>
            </div>
            <div class="col-sm modalidades">
                <h3>Dança</h3>
                <p>Este concurso visa avaliar as habilidades e a criatividade dos alunos participantes através da apresentação de uma coreografia avaliada nos domínios técnico e artístico.</p>
            </div>
            <div class="col-sm modalidades">
                <h3>Quem sabe... sabe</h3>
                <p> Este concurso visa icentivar os estudantes a terem a cultura de investigar e melhorar o seu desempenho acadêmico, dando a oportunidade às escolas de serem representadas por seus melhores quadros de estudantes.</p>
            </div>
            <div class="col-sm modalidades">
                <h3>Gaming</h3>
                <p>Descobriremos os melhores jogadores nas instituições de ensino, e iremos por meio deste concurso desenvolver o espirito de equipa, de criatividade, de inovação e curiosidade no seio dos estudantes.</p>
            </div>
        </div>
    </div>
</section>