<section class="ftco-section ftco-speakers" id="speakers-section">
    <div class="container">
        <div class="row justify-content-center pb-5">
            <div class="col-md-12 heading-section heading-section-white text-center ftco-animate">
                <span class="subheading">Nossos</span>
                <h2 class="mb-4">Parceiros</h2>
                <p></p>
            </div>
        </div>
        <div class="row" style="text-align: center;">

            <div class="col-sm">
                <img src="/intercolegial/web-files/images/brands/b1.png" alt="Parceiro" class="parceiros">
            </div>
            <div class="col-sm">
                <img src="/intercolegial/web-files/images/brands/am.png" alt="Parceiro" class="parceiros">
            </div>
            <div class="col-sm">
                <img src="/intercolegial/web-files/images/brands/b4.png" alt="Parceiro" class="parceiros">
            </div>
            <!--
            <div class="col-sm">
                <img src="/intercolegial/web-files/images/brands/b5.png" alt="Parceiro" class="parceiros">
            </div>
            <div class="col-sm">
                <img src="/intercolegial/web-files/images/brands/b7.png" alt="Parceiro" class="parceiros">
            </div>
            <div class="col-sm">
                <img src="/intercolegial/web-files/images/brands/b8.png" alt="Parceiro" class="parceiros">
            </div>
            <div class="col-sm">
                <img src="/intercolegial/web-files/images/brands/b9.png" alt="Parceiro" class="parceiros">
            </div>
            <div class="col-sm">
                <img src="/intercolegial/web-files/images/brands/b10.png" alt="Parceiro" class="parceiros">
            </div>
            <div class="col-sm">
                <img src="/intercolegial/web-files/images/brands/b11.png" alt="Parceiro" class="parceiros">
            </div>
            -->

        </div>
    </div>
</section>