
<!-- top navigation -->


<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">

                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <?php
                        if (isset($v_userInfo)) {
                            if (!$v_userInfo->getFoto() == null) {
                                $foto = $v_userInfo->getFoto(); //'m.jpg'; //($utilizador->getPessoa()->getGenero() == 'M' ? ('m.jpg') : ('f.jpg'));
                                echo '<img src="' . Geral::DIR_IMG_UTILIZADORES . $foto . '" alt="" />';
                            } else {
                                echo "<img src='https://www.intercolegialtinatune.co.ao/web-files/uploads/utilizadores/m.jpg' alt='' />";
                            }

                            //echo Method::retorna2nomes($v_userInfo->getNome());
                            echo $v_userInfo->getNome();
                        }
                        ?>
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="https://www.intercolegialtinatune.co.ao/Utilizador/perfil/<?php echo base64_encode("id") . '/' . base64_encode($v_userInfo->getId()) ?>"> Perfil</a></li>
                        <li><a href="https://www.intercolegialtinatune.co.ao/Login/logout"><i class="fa fa-sign-out pull-right"></i> Sair</a></li>
                    </ul>
                </li>



               

                <?php
                include_once 'app/views/public/alertas.phtml';
                ?>

            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->